### ISSUE TITLE
Support patching older major version of charm libraries

### ISSUE THREAD

**Issue by gruyaume** [canonical/charmcraft#1020]
**OVERVIEW**

`charmcraft publish-lib` doesn't allow to patch a major version of a library that is not the most recent. It would be reasonable and expected to be able to patch a charm library. For example, the [`tls-certificates-interface`](https://github.com/canonical/tls-certificates-interface/pull/30) has the following versions of a charm library published:
- 0.3
- 1.12
- 2.0

I would like to update lib v1 with a bug fix but it is impossible to publish to `1.13`. We are getting the following error:

```
The library tls_certificates has a wrong LIBAPI number, it's too high, Charmhub highest version is 2.0.
```

This is particularly important because major versions mean API and/or behaviour change. In cases where charms are already using a version of a library and there's a bug with it, we don't want to ask their authors to refactor their charm to use the newest major version, we'd want them to simply fetch the latest patch .

Taken from a discussion on this subject with @Roadmaster and @facundobatista 

```
if the latest you uploaded is v2.0, then the rules I see here are: you need to either push v2.1, or v3.0; pushing 1.13 is not going to work because 2.0 made that obsolete/deprecated from charmlibs point of view. This looks at the "tip" to determine what can come next; the tip is the highest from the list of revisions ordered by api and patch 
```

**Comment by maxiberta** [comment]
Just a heads up that this should now be working from the backend API service PoV. E.g. these upgrades are now allowed *simultaneously*:
- 0.3 => 0.4
- 1.12 => 1.13
- 2.0 => 2.1 (or 3.0)
