### ISSUE TITLE
Charmcraft build does not let you decide the output directory

### ISSUE THREAD

**Issue by camille-rodriguez** [canonical/charmcraft#103]
This might be more of a feature request, but it would be nice to be able to decide where we want the charm to end up. Currently, when running `charmcraft build`, the charm.charm ends up in the same directory. For functional tests, it is desirable to have a build directory where the charm to be tested will be located. I currently work around this by having a Makefile that moves the build charm to the desired location.

**Comment by lengau** [comment]
This has been fixed in the `pack` command
