### ISSUE TITLE
Expose libraries as pip installable packages

### ISSUE THREAD

**Issue by jdkandersson** [canonical/charmcraft#1036]
Currently, libraries for managing relationships have to be vendored (included as a source file) for a charm. This means that the charm repository includes duplicate code from a related charm which pollutes PRs and adds unnecessary code to the repository. An alternative is to publish the library files as pip installable packages from charmhub, which would also make things like version management easier

**Comment by lengau** [comment]
This is probably more appropriate for a request on charmhub, but it's also a topic I'm discussing with multiple teams about how to handle charmlibs as a whole. We're reconsidering the dependencies management.
