### ISSUE TITLE
Hook symlinks not created for deployments to environments running Juju < 2.8

### ISSUE THREAD

**Issue by gnuoy** [canonical/charmcraft#104]
I recently migrated a charm to use charmbuild and the charm deploy failed because only the install,start and upgrade-charm hooks were ever fired. After some head-scratching I believe this was down to the new ops dispatcher code relying on a version of Juju greater than the one I was using (2.7.6). If the operator framework requires a minimum Juju version then I think that charmcraft should inject `min-juju-version`  into the charms `metadata.yaml` at build time.

**Comment by chipaca** [comment]
There is no minimum requirement, but there might be bugs. Can you share more about how things broke?

**Comment by gnuoy** [comment]
The issue is that only the install, start and upgrade-charm hooks were ever fired.

Steps to reproduce:

1. Use charmcraft 0.3.0 to build charm.
2. Deploy charm into Juju 2.7 model.
3. After charms install hook has run check the hooks directory.

From a debug-hooks session during install hook:
```
# ./hooks/install 
2020-08-04 10:07:33,014 DEBUG    Operator Framework 0.7.0+6.g169794c up and running.
2020-08-04 10:07:33,073 INFO     Running legacy hooks/install.
2020-08-04 10:07:33,391 DEBUG    Operator Framework 0.7.0+6.g169794c up and running.
2020-08-04 10:07:33,470 DEBUG    Charm called itself via hooks/install.
2020-08-04 10:07:33,562 DEBUG    Legacy hooks/install exited with status 0.
2020-08-04 10:07:33,631 INFO     Using octopus class
2020-08-04 10:07:33,764 DEBUG    Emitting Juju event install.
lxc
2020-08-04 10:07:33,842 INFO     Installing into a container is not supported
2020-08-04 10:07:33,918 INFO     Updating status
lxc

# ls -l hooks/
total 2
-rwxr-xr-x 1 root root 93 Aug  4 10:03 install
-rwxr-xr-x 1 root root 93 Aug  4 10:03 start
-rwxr-xr-x 1 root root 93 Aug  4 10:03 upgrade-charm

# ls -l dispatch 
-rwxr-xr-x 1 root root 93 Aug  4 10:03 dispatch
# env | grep JUJU_DISPATCH_PATH
# 
```

I believe the issue is that due to the way the install hook is written
and the logic in the ops framework, a 'legacy' deployment is never
detected.

The install hook file created by charmcraft look like this:
```
#!/bin/sh

JUJU_DISPATCH_PATH="${JUJU_DISPATCH_PATH:-$0}" PYTHONPATH=lib:venv ./src/charm.py
```
Note that the JUJU_DISPATCH_PATH is **always** set. So when the operator
framework comes to check if it should use the dispatch method for executing the
hooks it checks if JUJU_DISPATCH_PATH is set and if there is a 'dispatch' file *1. 
Both these conditions are always true for a charmcraft built charm irrespective of
the Juju version running the charm.


https://github.com/canonical/operator/blob/master/ops/main.py#L170

**Comment by afreiberger** [comment]
It appears if you symliink any of the hooks/<hook-name> files to your entrypoint (../src/charm.py) that it'll fix those up to be dispatch-aware hooks at build time.  It would be very handy if charmcraft could read the entrypoint and create these automatically for any observed methods.

i.e. if I have:
```
class MyCharm(CharmBase):

    def __init__(self, *args):
        super().__init__(*args)
        self.framework.observe(self.on.cluster-relation-changed, self.on_cluster_relation_changed)
```

I would expect that a hooks/cluster-relation-changed file would be created by charmcraft build.

**Comment by chipaca** [comment]
@afreiberger those are created by operator automatically on first hook run (if not using `dispatch`)

**Comment by chipaca** [comment]
This issue was fixed by a change to operator (tracked in operator#362), released as part of 0.8.

**Comment by chipaca** [comment]
@afreiberger @auria are you seeing any issues that lead you to ask for what you did?
I'd like some context to understand, please.

**Comment by afreiberger** [comment]
Developing a new charm, `charm proof` gives warning that hooks are not present for relations defined in metadata.yaml.

Realizing charm proof is just a bit of a smoke-test in the case of an operator charm, we'll do some tests to see if latest operator code does create these links upon charm deployment.
