### ISSUE TITLE
Package removed from `requirements.txt` not removed without `charmcraft clean`

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/charmcraft#1059]
Version: `2.2.0`

## Steps to reproduce
1. `git clone https://github.com/carlcsaposs-canonical/charm-bug-report.git`
2. `cd charm-bug-report/`
3. `git checkout origin/remove-dep-1`
4. `charmcraft pack`
5. `git checkout origin/remove-dep-2`
6. `charmcraft pack`
7. Unzip *.charm & `ls venv/`

## Expected behavior
tenacity should not be in `venv/`

## Actual behavior
tenacity is in `venv/`

## Notes
Appears related to #1058

**Comment by syu-w** [comment]
I would say if you removed deps, `charmcraft clean` should be used. Since `pip uninstall` will not able to uninstall everything from the package.
