### ISSUE TITLE
Symlinks for directories are not correctly created in Windows

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#1066]
The `charm_builder.py` code, when handling generic paths, create symlinks doing `dest_path.symlink_to(relative_link)`, same thing for files and directories.

In Windows, it needs to be told if the symlink is for a file or a directory. When the case of a dir, it should be `dest_path.symlink_to(relative_link, target_is_directory=True)`

**Comment by lengau** [comment]
Superseded by https://github.com/canonical/charmcraft/issues/1810
