### ISSUE TITLE
No easy way to publish a charm built with charmcraft to jaas.ai 

### ISSUE THREAD

**Issue by camille-rodriguez** [canonical/charmcraft#109]
It is necessary to be able to publish a charm to the jaas.ai store, to be able to do a juju deploy cs:~owner/charm-name.
To do so, one needs to build the charm, push it and release it. However, the built version of the charm that appears in the `build` directory when doing `charmcraft build` uses symlinks, which is not accepted by `charm push`. Here is the error I got :
```
$ charm push .
ERROR cannot open charm archive: cannot create entity archive: symlink "actions.yaml" is absolute: "/home/crodriguez/Projects/charm-iscsi-connector/actions.yaml"
crodriguez@camille-ubuntu:~/Projects/charm-iscsi-connector/build$ ls -la
total 28
drwxrwxr-x  4 crodriguez crodriguez 4096 Aug  6 10:38 .
drwxrwxr-x 10 crodriguez crodriguez 4096 Aug  6 10:38 ..
lrwxrwxrwx  1 crodriguez crodriguez   60 Aug  6 10:38 actions.yaml -> /home/crodriguez/Projects/charm-iscsi-connector/actions.yaml
lrwxrwxrwx  1 crodriguez crodriguez   59 Aug  6 10:38 config.yaml -> /home/crodriguez/Projects/charm-iscsi-connector/config.yaml
-rwxrwxr-x  1 crodriguez crodriguez   93 Aug  6 10:38 dispatch
drwxrwxr-x  2 crodriguez crodriguez 4096 Aug  6 10:38 hooks
lrwxrwxrwx  1 crodriguez crodriguez   61 Aug  6 10:38 metadata.yaml -> /home/crodriguez/Projects/charm-iscsi-connector/metadata.yaml
lrwxrwxrwx  1 crodriguez crodriguez   51 Aug  6 10:38 src -> /home/crodriguez/Projects/charm-iscsi-connector/src
lrwxrwxrwx  1 crodriguez crodriguez   57 Aug  6 10:38 templates -> /home/crodriguez/Projects/charm-iscsi-connector/templates
drwxrwxr-x 10 crodriguez crodriguez 4096 Aug  6 10:38 venv
```

I also tried to simply push to the store the whole charm, from root, but juju does not understand that it is supposed to deploy the built folder. The charm ends up in an "unknown" state. 

A workaround is to pull the charm locally, and then point in the bundle the .charm zip file, but that is not a sustainable option. Another workaround suggested would be to do `charmcraft build && rm -r build && mkdir build && unzip -d build *.charm` and then publish the result to the store, which could work but is also not an ideal solution.

**Comment by facundobatista** [comment]
The links issue are solved already in master (you can try it from the snap's `edge` channel). Please check if with that fix it's enough, or which is the problem.

We're interested in solving this use path, but it's not clear to us how this will evolve when we have multi-arch building, so let's keep talking.

**Comment by camille-rodriguez** [comment]
I've tested with the latest snap version today and I was able to publish to the store without any workaround, from the build directory. I think we can close this issue, unless you wanted to keep it open for further discussion?

**Comment by facundobatista** [comment]
I think we can close it, thanks!
