### ISSUE TITLE
Remove authentication for accessing information publicly accesible

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/charmcraft#1124]
### What needs to get done

 Hi!,

  There are several operations like list-lib and fetch-lib
  that expose information that is already publicly available. Could
  authentication be removed from these? Also, it would probably make
  sense to do the same for querying revisions, resource-revisions and
  status.

### Why it needs to get done

  We are running several checks in our CI that currently require a
  charmhub token to authenticate. This limits community contributions
  given that forks would require their own token.
This will also improve dev experience

**Comment by sergiusens** [comment]
Fetch lib should already allow anonymous GETs, is that not working?

**Comment by arturo-seijas** [comment]
> Fetch lib should already allow anonymous GETs, is that not working?

It is. Thanks!
