### ISSUE TITLE
`charmcraft init`: issues with --profile docs, default profile, and default charm.py links

### ISSUE THREAD

**Issue by tmihoc** [canonical/charmcraft#1128]
### Bug Description

I wanted to initialize a machine charm. I looked up the `charmcraft init` help: https://juju.is/docs/sdk/charmcraft-init . (Issue 1) It mentioned the `--profile` option but not what arguments it could take (other than to say it defaults to `simple`, which was also not defined). I gave up and just ran the command without selecting a profile. Then I noticed (Issue 2) the charm it had initialized by default was a Kubernetes charm. Also, (issue 3) the comment at the top of the `charm.py` file linked to quick-start guide (https://discourse.charmhub.io/t/4208) that is not published in the docs and which doesn't really make much sense (e.g., it contains instructions on how to install `charmcraft` and how to run `charmcraft init` but, if you've come to this page from the charm.py produced by `charmcraft init`, then you already know how to do all that).

I think we should document all the possible arguments for `--profile`, not apply any default to `charmcraft init` (prompt the user to choose), and link only to official docs.

### To Reproduce

Issue 1: Run `charmcraft init --help` or visit https://juju.is/docs/sdk/charmcraft-init .
Issue 2: Run `charmcraft init`.
Issue 3: Inspect the contents of the `charm.py` file generated by `charmcraft init`.

### Environment

Not applicable.

### charmcraft.yaml

```shell
Not relevant.
```

### Relevant log output

```shell
Not relevant.
```

**Comment by sergiusens** [comment]
`charmcraft help init` should detail each profile, maybe with links to those charm types if they exists

The charm.py link needs to be updated

**Comment by syu-w** [comment]
The charm.py link has been updated to https://juju.is/docs/sdk/create-a-minimal-kubernetes-charm

https://github.com/canonical/charmcraft/pull/1158
