### ISSUE TITLE
LXD race condition when packing multiple charms simultaneously

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/charmcraft#1132]
### Bug Description

When we run our CI we get following error:

```
Traceback (most recent call last):
  File "/home/runner/work/kfp-operators/kfp-operators/tests/integration/test_bundle.py", line 39, in test_build_and_deploy
    built_charms = await ops_test.build_charms(*charms_to_build.values())
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/bundle-integration/lib/python3.8/site-packages/pytest_operator/plugin.py", line 1028, in build_charms
    charms = await asyncio.gather(
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/bundle-integration/lib/python3.8/site-packages/pytest_operator/plugin.py", line 1011, in build_charm
    raise RuntimeError(
RuntimeError: Failed to build charm /home/runner/work/kfp-operators/kfp-operators/charms/kfp-viz:
Packing the charm.
Launching environment to pack for base name='ubuntu' channel='20.04' architectures=['amd64'] (may take a while the first time but it's reusable)
charmcraft internal error: LXDError(brief="Failed to create project 'charmcraft'.", details='* Command that failed: \'lxc --project charmcraft project create local:charmcraft\'\n* Command exit code: 1\n* Command standard error output: b\'Error: Failed creating project "charmcraft": Failed adding database record: This "projects" entry already exists\\n\'', resolution=None)
Full execution log: '/home/runner/.local/state/charmcraft/log/charmcraft-20230628-102516.095719.log'
```

here is an example run:
https://github.com/canonical/kfp-operators/actions/runs/5399918594/jobs/9807754324

### To Reproduce

I cannot reproduce it locally, but this is in our CI: https://github.com/canonical/kfp-operators/actions/runs/5399918594/jobs/9807754324

### Environment

lxd 5.15-3fe7435 

Ubuntu 20.04

### charmcraft.yaml

```shell
# Learn more about charmcraft.yaml configuration at:
# https://juju.is/docs/sdk/charmcraft-config
type: "charm"
bases:
  - build-on:
    - name: "ubuntu"
      channel: "20.04"
    run-on:
    - name: "ubuntu"
      channel: "20.04"
parts:
  charm:
    charm-python-packages: [setuptools, pip]  # Fixes install of some packages
```

### Relevant log output

```shell
-
```

**Comment by beliaev-maksim** [comment]
[juju-kubernetes-charmcraft-logs.zip](https://github.com/canonical/charmcraft/files/11895062/juju-kubernetes-charmcraft-logs.zip)

**Comment by beliaev-maksim** [comment]
@mr-cal tests run sequentially. However, I can expect that ops_test builds in parallel

**Comment by DnPlas** [comment]
I think I'm still hitting this issue [here](https://github.com/canonical/kfp-operators/actions/runs/5586616307/jobs/10210877250#step:14:687). Did https://github.com/canonical/craft-providers/pull/357 resolved it?

**Comment by lengau** [comment]
@DnPlas the latest edge and the candidate 2.4.0 should now have this particular error resolved. It's possible we'll uncover further issues though.

**Comment by beliaev-maksim** [comment]
@lengau we definitely still have an issue with
`charmcraft internal error: LXDError(brief="Failed to copy instance 'local:charmcraft-knative-serving-162750-0-0-amd64' to 'local:base-instance-charmcraft-buildd-base-v10-07bde40a62a827cdc5a4'.", details='* Command that failed: \'lxc --project charmcraft copy local:charmcraft-knative-serving-162750-0-0-amd64 local:base-instance-charmcraft-buildd-base-v10-07bde40a62a827cdc5a4\'\n* Command exit code: 1\n* Command standard error output: b\'Error: Failed creating instance record: Instance is busy running a "create" operation\\n\'', resolution=None)`

**Comment by sergiusens** [comment]
This has been solved

**Comment by DnPlas** [comment]
I'm still running into the same issue @sergiusens, look [here](https://github.com/canonical/istio-operators/actions/runs/6380883472/job/17316144330#step:4:120). Are there any updates on this issue? I don't think we can close it.

**Comment by sergiusens** [comment]
@DnPlas this is fixed in code and in charmcraft from edge
