### ISSUE TITLE
Be able to leverage default-installed packages

### ISSUE THREAD

**Issue by jameinel** [canonical/charmcraft#114]
I'm not sure if we want to do this or not. But the Juju operator image that is used for operators comes with a few set of python libraries baked in:
https://github.com/juju/juju/blob/develop/caas/Dockerfile
https://github.com/juju/juju/blob/develop/caas/requirements.txt

Yaml, pip, distutils are fairly obvious, but it also includes charmhelpers, charms.reactive and the kubernetes library.

It may be that we don't want to expect them to be there/expose them to the charm. Though a lot of the K8s discussion that I've seen is about providing a 'base' that Charms can be built against. (Whether that is current style, or 'new style' in both cases there would be expectations about the environment that the charm can depend upon.)

I'm bringing this up in response to:
https://discourse.juju.is/t/implementing-k8s-resources-in-a-charm-that-are-not-supported-by-pod-spec/3412

Where the proposed solution is that you can "import kubernetes", since it comes packaged in the base image.

That said, IMO it seems much more obvious to include it in a *charm's* requirements.txt rather than depending on a particular version that Juju has decided is right for everyone. (Though I'd like charms to not get bloated by having double copies of system libs, etc.)

This issue is mostly to raise awareness in the team so we can debate how we want it to function.

**Comment by facundobatista** [comment]
The built charm includes installed libraries (those defined in `requirements.txt`), but the charm execution is not affected by any restriction (like a virtualenv).

So it's up to the developer to use a library from the system.

In general I agree we should discourage that, as there's far more control in specifying the needs libs in the requirement file, but in principle the developer could rely on the system for complex stuff (not thinking in a base image, but maybe something more complex specifically built in some environments).

So, again, it's up to the developer. Note that in the future they will have more control and options when we integrate the full lifecycle from Snapcraft.

I'm closing this, but we can reopen it if in the future we have needs we can action on (specially after the whole juju-kubernates settled).
