### ISSUE TITLE
Template should not use undocumented .flake8 file

### ISSUE THREAD

**Issue by stub42** [canonical/charmcraft#119]
`.flake8` is not a documented way of configuring flake8. The charm template should put flake8 configuration in one of the blessed locations, `setup.cfg` or `tox.ini`, to help developers unfamiliar with the tool.

**Comment by facundobatista** [comment]
In the tool [doc page about config](https://flake8.pycqa.org/en/latest/user/configuration.html) it says that the config may be located in `In your project in one of setup.cfg, tox.ini, or .flake8.`...

**Comment by stub42** [comment]
Aha... and the man page in those docs doesn't mention config file locations at all. So it is just missing from the Ubuntu man page.
