### ISSUE TITLE
Bundle spread tests are failing

### ISSUE THREAD

**Issue by lengau** [canonical/charmcraft#1262]
### What needs to get done

Figure out why and fix the tests. It looks like it's just because of yaml formatting differences.

https://github.com/canonical/charmcraft/actions/runs/6210409286/job/16858681409

- [ ] google:ubuntu-22.04-64:tests/spread/charms/bundle:argo
- [ ] google:ubuntu-22.04-64:tests/spread/charms/bundle:istio
- [ ] google:ubuntu-22.04-64:tests/spread/charms/bundle:kfp
- [ ] google:ubuntu-22.04-64:tests/spread/charms/bundle:notebook_operators

### Why it needs to get done

They used to succeed, so this may be an introduced regression

**Comment by syu-w** [comment]
All bundles build successful. There are some yaml format changes but data are the same.
However, 
https://github.com/canonical/charmcraft/blob/f23532796510ad85517d4a7a98c30db58676fc70/tests/spread/charms/bundle/task.yaml#L56-L62

failing that those bundle do not have `charm: ${PWD}` but use something like `charm: ch:argo-controller`
