### ISSUE TITLE
Handle bundles when interacting with the store

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#128]
We need to handle bundles properly in all the operations related to the store.

Most of that should be ok already, but for sure we need to improve some details:

- in the `register` command, give the option to register the name for a bundle. The idea is to provide a `--type` option that will allow the `charm` and `bundle` values (and possibly more in the future, like `stack`); this `--type` can be avoided if the project from where the command is issued can be identified as one or the other, otherwise it's mandatory.

- in the `names` command, add a column with the type of the package.

- in the `build` command, we should support a `metadata.yaml` not being there but a `bundle.yaml`: in that case just build a zip named `.bundle` with everything that is there (pretty much like we do for charms) but without building dependencies, or creating hooks/dispatch, etc. So in reality build will have two modes ("charm" and "bundle"), decided automatically after what is found in the project. Note also that some options are valid for the different modes (like `--from`) but others are not (like `--entrypoint`): in the latter cases we need to raise an error.

- in the `upload` command, we need to rename current `--charm-file` to be `--file` (supporting both charm and bundle files), and improve what is automatically detected from the project where the command is issued (we can guess the name from a possible `metadata.yaml`, for example, but not from a `bundle.yaml`).

**Comment by facundobatista** [comment]
We went to a more explicit model regarding the commands...

These are the specific ones:

- `register-bundle`
- `upload-bundle`
- `release-bundle`

These are still under study (if to be shared, or new ones be created):

- `revisions`
- `status`

OTOH, `names` if for "everything registered by the user", so it makes totally sense to work for "everything".

**Comment by hmlanigan** [comment]
Can we have a bundle init like we have a charm init?

**Comment by facundobatista** [comment]
Everything landed. Still to work on some docs.

**Comment by facundobatista** [comment]
> Can we have a bundle init like we have a charm init?

No really needed, as normally we ask Juju to create the bundles, [see here](https://juju.is/docs/charm-bundles).

**Comment by facundobatista** [comment]
We got [docs](https://charmhub.io/tutorials/how-to-work-with-bundles-in-charmcraft#1-introduction).
