### ISSUE TITLE
Handle multiple platforms for channel map in status

### ISSUE THREAD

**Issue by matiasb** [canonical/charmcraft#129]
If a charm support multiple series (platforms), there could be different released revisions for each of them (eg. revision 1 released to (`stable`, `xenial`) and revision 2 to (`stable`, `focal`)). FWIW, this is similar for snaps, snapcraft and multiple architectures

`charmcraft` is currently rendering one released value for each channel, ignoring the platform.

**Comment by maxiberta** [comment]
Note that charm "platforms" is being superseded by "bases". Support for platforms (unused at the moment) is being dropped from Charmhub (`/v1/<namespace>/<name>/revisions` and `/v1/<namespace>/<name>/releases`). Eventually, bases will need to be exposed for a complete `status` output.
