### ISSUE TITLE
pip wheel cache ignored

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/charmcraft#1374]
## Expected behavior
After charmcraft LXC containers are deleted, the pip cache added in charmcraft 2.5 is used in the next pack

## Actual behavior
After charmcraft LXC containers are deleted, the next pack takes the same amount of time if the pip cache is present or missing

### To Reproduce

```
sudo snap install charmcraft --channel candidate --classic
git clone https://github.com/canonical/mysql-router-k8s-operator
cd mysql-router-k8s-operator
tox run -e pack-wrapper
mv requirements-last-build.txt requirements.txt
charmcraft pack -v
lxc --project charmcraft ls
lxc --project charmcraft delete base-instance-charmcraft-buildd-base-v20-2046f14fb4a00aa9ce50
lxc --project charmcraft delete charmcraft-mysql-router-k8s-520528-0-0-amd64
time charmcraft pack -v
lxc --project charmcraft delete base-instance-charmcraft-buildd-base-v20-2046f14fb4a00aa9ce50
lxc --project charmcraft delete charmcraft-mysql-router-k8s-520528-0-0-amd64
rm -r ~/snap/charmcraft/common/cache/charmcraft/
time charmcraft pack -v
```

### Environment

Ubuntu 22.04
charmcraft snap rev 1736

### charmcraft.yaml

```shell
# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

type: charm
bases:
  - build-on:
      - name: "ubuntu"
        channel: "22.04"
    run-on:
      - name: "ubuntu"
        channel: "22.04"
parts:
  charm:
    override-pull: |
      craftctl default
      if [[ ! -f requirements.txt ]]
      then
          echo 'ERROR: Use "tox run -e build" instead of calling "charmcraft pack" directly' >&2
          exit 1
      fi
    charm-entrypoint: src/kubernetes_charm.py
    prime:
      - charm_version
      - workload_version
      - scripts
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
      - rustc
      - cargo
```

### Relevant log output

```shell
See first comment
```

**Comment by sergiusens** [comment]
Why are you deleting the base?

**Comment by lengau** [comment]
Updates:

* When pip 22 is used, `--no-binary=:all:` (old behaviour) will use the wheel cache, but `--no-binary=[list of packages]` ignores the wheel cache. This is not the case with pip 23
* On Ubuntu 22.04, we use pip from apt (22.0.2), but on 20.04, we install a newer pip (built-in is 20.0.2), which gets us pip 23.
* We don't have a way to set the pip version to use in the charm plugin

**Comment by lengau** [comment]
2.5.4 brings pip >= 23, which my testing indicates changes the desired pip behaviour.

**Comment by lengau** [comment]
Thanks for the confirmation @carlcsaposs-canonical !

I'm going to close this one for now, but I'll reopen it if we get any regression reports on 2.5.4
