### ISSUE TITLE
'charm-strict-dependencies' requires at least one requirements file. in field 'parts.charm.charm-strict-dependencies'

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/charmcraft#1389]
### Bug Description

I'm guessing `charm-strict-dependencies` defaults to requirements.txt during charmcraft pack? Looks like the same default doesn't apply to `charmcraft clean`

### To Reproduce

charmcraft installed from edge (rev 1824 2.5.0.post16+git23bf390)
1. clone https://github.com/canonical/mysql-router-k8s-operator
2. charmcraft pack
3. charmcraft clean

```
Bad charmcraft.yaml content:
- 'charm-strict-dependencies' requires at least one requirements file. in field 'parts.charm.charm-strict-dependencies'                                                                                                                              
Full execution log: '/home/ubuntu/.local/state/charmcraft/log/charmcraft-20231124-090230.749172.log'    
```

### Environment

Ubuntu 22.04

### charmcraft.yaml

```shell
# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

type: charm
bases:
  - build-on:
      - name: "ubuntu"
        channel: "22.04"
    run-on:
      - name: "ubuntu"
        channel: "22.04"
parts:
  charm:
    override-pull: |
      craftctl default
      if [[ ! -f requirements.txt ]]
      then
          echo 'ERROR: Use "tox run -e build" instead of calling "charmcraft pack" directly' >&2
          exit 1
      fi
    charm-entrypoint: src/kubernetes_charm.py
    prime:
      - charm_version
      - workload_version
      - scripts
    charm-strict-dependencies: true
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
      - rustc
      - cargo
```

### Relevant log output

[charmcraft-20231124-090230.749172.log](https://github.com/canonical/charmcraft/files/13457115/charmcraft-20231124-090230.749172.log)
[charmcraft-20231124-084822.286563.log](https://github.com/canonical/charmcraft/files/13457116/charmcraft-20231124-084822.286563.log)

**Comment by lengau** [comment]
Thanks for the report! This bug is actually in the `pack` command, as when `charm-strict-dependencies: true` is set it shouldn't be magicking up `requirements.txt` for you (instead requiring an explicit list of requirements files).

**Comment by lengau** [comment]
The only way I've been able to reproduce this is by deleting `requirements.txt`, but then both `pack` and `clean` complain about the lack of a requirements file. Could you check the state of the `requirements.txt` file when this happens?

I'm adjusting the 3.0 behaviour so it requires the `requirements.txt` file to be explicitly mentioned in strict mode (not going to change that in the 2.x branch).

**Comment by lengau** [comment]
Ah, looking at `tox.ini` I've figured it out. The `commands_post` includes moving `requirements.txt`. I've made [a PR](https://github.com/canonical/mysql-router-k8s-operator/pull/175) to create a `clean` environment to work around these conflicting requirements for now. 

We might be able to make the `clean` command less strict about the existence of requirements.txt later, but it's sadly not feasible right now.

**Comment by lengau** [comment]
OK @taurus-forever , @carlcsaposs-canonical , I'm convinced :-)

The fix probably won't make it into 3.0.0, but I'm going to consider options for how to better resolve this in Charmcraft.

**Comment by lucasgameiroborges** [comment]
Hello! Just checking in this issue, I faced the same issue during my onboarding tasks.

**Comment by taurus-forever** [comment]
@lengau can you please share the plans for the fix here?

We would like to avoid workarounds on our side, ETA will help us a lot. Thank you!
