### ISSUE TITLE
Strict dependencies prevents charm from building

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/charmcraft#1456]
### Bug Description

`ModuleNotFoundError: No module named 'markupsafe'` when building charm with `charm-strict-dependencies: true`

### To Reproduce

```
git clone https://github.com/canonical/mysql-router-operator
git checkout with-hashes
tox run -e pack-wrapper
mv requirements-last-build.txt requirements.txt
charmcraft pack
```

### Environment

Ubuntu 22.04

### charmcraft.yaml

```shell
# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

type: charm
bases:
  # Whenever "bases" is changed:
  # - Update tests/integration/conftest.py::pytest_configure()
  # - Update .github/workflow/ci.yaml integration-test matrix
  - build-on:
      - name: "ubuntu"
        channel: "20.04"
    run-on:
      - name: "ubuntu"
        channel: "20.04"
  - build-on:
      - name: "ubuntu"
        channel: "22.04"
    run-on:
      - name: "ubuntu"
        channel: "22.04"
parts:
  charm:
    override-pull: |
      craftctl default
      if [[ ! -f requirements.txt ]]
      then
          echo 'ERROR: Use "tox run -e build" instead of calling "charmcraft pack" directly' >&2
          exit 1
      fi
    charm-strict-dependencies: true
    charm-entrypoint: src/machine_charm.py
```

### Relevant log output
[charmcraft-20240103-154031.230848.log](https://github.com/canonical/charmcraft/files/13820882/charmcraft-20240103-154031.230848.log)

**Comment by lengau** [comment]
Thanks for the report! This is a charmcraft bug in that it's not always grabbing the correct version of pip 🙃 

You can replicate the failure by firing up a venv with pip 20.0.2 and running `pip install --no-binary=jinja2,markupsafe jinja2`

The Jammy build should still work though.

When getting pip, we need to specify that we want `pip>=23.2.1` (here: https://github.com/canonical/charmcraft/blob/2567c661d0ba99fad742ff1e73cbcf6431addbd9/charmcraft/charm_builder.py#L240)

**Comment by ca-scribner** [comment]
I'm hitting this as well - is there a workaround that a charm can use to sort this out temporarily?
