### ISSUE TITLE
Limit spread tests to runners that have spread

### ISSUE THREAD

**Issue by lengau** [canonical/charmcraft#1463]
### What needs to get done

Get an appropriate tag for the self-hosted runners with spread access and limit the spread tests to run on those.

Example:

* Job that has spread: https://github.com/canonical/charmcraft/actions/runs/7401809000/job/20138772548
* Job that failed because it got put on a runner without spread: https://github.com/canonical/charmcraft/actions/runs/7401809000/job/20138772744

### Why it needs to get done

Right now we have to re-run spread tests because they sometimes get put onto runners that don't have spread available

**Comment by lengau** [comment]
@sergiocazzolato do the *craft runners with spread have a label or group or something we could require in `runs-on` to ensure our spread tests only run on those runners?

**Comment by sergiocazzolato** [comment]
@lengau Hi, someone with admin permissions in this project can add labels in the page 
https://github.com/canonical/charmcraft/settings/actions/runners/<RUNNER_ID>
Then, for example, you can use the label 'spread-installed' to filter runners for the desired jobs doing `runs-on: [self-hosted, spread-installed]`
