### ISSUE TITLE
Hide extensions commands

### ISSUE THREAD

**Issue by lengau** [canonical/charmcraft#1495]
### What needs to get done

Mark `expand-extensions` and `list-extensions` as hidden in the 2.x branch

### Why it needs to get done

2.x doesn't have any extensions so we don't need to confuse people by making that behaviour visible.

**Comment by tmihoc** [comment]
@lengau We now do have an extension and have also documented extensions (https://juju.is/docs/sdk/manage-extensions ; upcoming tutorial track featuring the flask-framework extension), so I think this can be closed.
