### ISSUE TITLE
Publish all releases on PyPI

### ISSUE THREAD

**Issue by bittner** [canonical/charmcraft#1579]
### What needs to get done

There are releases of the charmcraft Python package on GitHub, which are not on PyPI.

### Why it needs to get done

It's more obvious, more natural to install the Python package from PyPI.

A release on GitHub suggests that there is also a release on the canonical Python package platform. Not keeping the releases in sync creates additional confusion.

**Comment by tigarmo** [comment]
Hi @bittner. Out of curiosity, what is your use-case for consuming Charmcraft as a Python package (instead of the snap)?

**Comment by bittner** [comment]
Most importantly, installing a snap in a `Dockerfile` is not trivial. I maintain [a charmcraft container image](https://gitlab.com/painless-software/docker/charmcraft/) for pipeline automation, and I'm happy it can be installed just as a normal Python package.

Apart from that, I want to work on Juju Charms preferably with a pure Python tool chain. Also, I think it's fair to assume that developers using a popular (Open Source) Python package expect that it can, primarily, be installed from PyPI.

As for another argument, _I_ use Ubuntu, and of course, _I_ can install a snap - at least on my development machine -, but I have other people in the teams that I work with that prefer to use macOS or Windows. How can I convince them that it's great to work with Juju Charms when it requires them to abandon their preferred environment?

**Comment by tigarmo** [comment]
Thank you for the reply, this is very interesting. I definitely hear you on the Docker restriction on snaps, and I didn't know people were able to effectively use Charmcraft as a Python package in non-Linux environments.

**Comment by bittner** [comment]
> I didn't know people were able to effectively use Charmcraft as a Python package in non-Linux environments.

TBH, I've not tried charmcraft on anything but Ubuntu, but I assumed that the OS-independent nature of Python is why charmcraft was implemented with it. Not sure what charmcraft features would require to be limited to Linux, or even Ubuntu. The snap packaging, OTOH, certainly is a limiting factor. A friend of mine who uses Arch Linux preferred to come up with [a Vagrant setup](https://gitlab.com/painless-software/cicd/examples/charmed-django-charm/-/blob/main/Vagrantfile) (with Ubuntu) for charm development.

As by the example in https://github.com/canonical/charmcraft/pull/1580#issuecomment-2030611216, the recent improvements on charmcraft were good to have released on PyPI, so that a few more CI use cases could be made possible. :100:

**Comment by tigarmo** [comment]
> Not sure what charmcraft features would require to be limited to Linux, or even Ubuntu

I was thinking of building using managed lxd instances, but if you're using this in a Docker container that wasn't your use case.

**Comment by chenrui333** [comment]
homebrew does prefer pure pypi toolchain as well, I think it is good to publish sdist to pypi for downstream packaging manager use in general

**Comment by chenrui333** [comment]
only luck on this thread?

**Comment by bittner** [comment]
> any luck on this thread?

@tmihoc Any chance we can get the (latest) versions missing on PyPI uploaded? The [automation](https://github.com/canonical/charmcraft/blob/main/.github/workflows/publish-pypi.yaml) is now in place. The publishing command ([`tox -e package -- upload`](https://github.com/canonical/charmcraft/blob/main/tox.ini#L167)) can also be run locally the same way.

**Comment by tmihoc** [comment]
@bittner : @lengau might be able to help.

**Comment by lengau** [comment]
@bittner I'll be releasing 2.7.1 and 3.1.0 to PyPI with this shortly.

**Comment by lengau** [comment]
All releases up to 2.7.0 and 3.0.0 have been backfilled on pypi. Marking as resolved.

**Comment by bittner** [comment]
Great, thanks for filling the gaps! 💯 

Looking forward to seeing the [publish workflow](https://github.com/canonical/charmcraft/actions/workflows/publish-pypi.yaml) run for the first time in this repo. 🤖
