### ISSUE TITLE
Default `charm` or `bundle` part is not added if `parts` is defined but empty in `charmcraft.yaml`.

### ISSUE THREAD

**Issue by weiiwang01** [canonical/charmcraft#1616]
### Bug Description

Currently, the default charm part is added to the charmcraft project configuration using the Pydantic model validator `charmcraft.models.project.CharmcraftProject.preprocess_parts`. However, because Pydantic validators are executed in the order they are defined, and the `parts` field is defined in the parent class `craft_application.models.project.Project` while the `type` field is defined in the child class, the validator for `parts` field will always execute before validator for `type` field. 

This means the `type` attributes will never exist in the `values` parameter of `preprocess_parts` validator function. This causes the `parts` not to be added if the `parts` in the charmcraft project file are defined as `{}`. However, when the `parts` field is not defined in `charmcraft.yaml`, its value will be `None`, and the default value of `charmcraft.models.project.BasesCharm.parts` will take effect, setting the parts to `{"charm": {"plugin": "charm", "source": "."}}`.

### To Reproduce

To reproduce this issue, create a `charmcraft.yaml` with the following parts. It will not execute the `charm` part when packed:

```
parts: {}
```

### Environment

Ubuntu 22.04 LTS

### charmcraft.yaml

```shell
name: charm
type: charm
bases:
  - build-on:
    - name: ubuntu
      channel: "22.04"
    run-on:
    - name: ubuntu
      channel: "22.04"
summary: A test charm.
description: A test charm.

# important
parts: {}
```

### Relevant log output

```shell
n/a
```

**Comment by sergiusens** [comment]
ah, this was meant to be the original design. @lengau we need to do some design work here to see if we finally make charm and bundle actual extensions

**Comment by weiiwang01** [comment]
> ah, this was meant to be the original design. @lengau we need to do some design work here to see if we finally make charm and bundle actual extensions

Gotcha, thanks, the issue now is that when extensions are applied, the parts is set to `{}` even if the extension does not modify the parts. So, maybe we can find a workaround to set the parts to `None` if they are empty after the extension has been applied?
