### ISSUE TITLE
Stop including in the charm file whatever is in the project

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#170]
We took a different path in the past (see #39), but for security reasons, we need to stop including whatever file/dirs are in the project, as it happened several times in the past that "secrets" (tokens, keys, etc) are included and published without realising it.

Before we switch back to this model, though, we need to allow the author to include specific files in the project, in case she needs some structures we're not including by default. See related #5.

**Comment by johnsca** [comment]
This also leads to the generated `.charm` file often getting included in subsequent builds of the charm.  It appears that charmcraft does support the [`.jujuignore` file](https://discourse.charmhub.io/t/deploying-charms-offline/1069#heading--ignoring-files), so it might be better to just document that better, although I think that the `.charm` file should be added to the default, and maybe `.gitignore` and similar files should be honored as well?

**Comment by facundobatista** [comment]
There are several minor improvements for the current situation, yes, but we need to depart from it. 

We just grown support for a configuration file that can be used to specify what can be included in the charm file beyond the bare minimum, so we're in a good position now to tackle this issue.

**Comment by Vultaire** [comment]
Another path to consider here is that, not only do subsequent builds include the previous built files if they're in the project dir (which could be worked around via "make clean" perhaps), but if using charmcraft.yaml with multiple bases, the same issue will occur.

I have a charm which targets Bionic and Xenial, and "charmcraft build" results in the 18.04 charm containing the entire 20.04 charm as well.  I suppose I can ```zip -d <charm> <extra file>``` to manually clean up the .charm files, assuming there isn't some sort of checksum which would be violated by doing such a modification to the .charm files.

**Comment by heitorPB** [comment]
> I have a charm which targets Bionic and Xenial, and "charmcraft build" results in the 18.04 charm containing the entire 20.04 charm as well.

I had a similar issue. I added `*.charm` to the `.jujuignore` file to solve it.

**Comment by facundobatista** [comment]
The fix for this is already landed. `charmcraft` by default will include only some mandatory charm files (e.g. `metadata.yaml`) or well known optional ones (e.g. `version`).

If you want to include other files or directories, those should be configured in `charmcraft.yaml`, for example:

```
parts:
    charm:
        prime: 
          - to_be_included.bin
```

**Comment by heitorPB** [comment]
@facundobatista could you elaborate on what will be included in the charms? Is this documented somewhere?

**Comment by facundobatista** [comment]
Yes! we have a post explaining everything better here: https://discourse.charmhub.io/t/charm-packing-will-not-include-all-files-by-default-anymore/4924/9
