### ISSUE TITLE
charmcraft `3.1.1` "successfully" packs charm, but python packages are missing in the venv

### ISSUE THREAD

**Issue by ca-scribner** [canonical/charmcraft#1781]
### Bug Description

Packing the grafana-agent charm in charmcraft 3.1.1 appears to complete successfully, but results in a charm that has packages missing in the charm's venv.  Packing works fine in charmcraft 2.7.x

### To Reproduce

```
# Download a "control" charm
juju download grafana-agent --channel latest/edge

# Pack something new to compare
git clone git@github.com:canonical/grafana-agent-operator.git
charmcraft pack

# inspect the .charm file's venv.  The newly packed charm will have a much emptier venv
```

### Environment

ubuntu 24.04

### charmcraft.yaml

[charmcraft.yaml](https://github.com/canonical/grafana-agent-operator/blob/main/charmcraft.yaml)

### Relevant log output

[pastebin](https://pastebin.ubuntu.com/p/wztzCvywwf/)

**Comment by lengau** [comment]
Thanks for the report! 

This looks like the grafana charm is depending on a bug in the older strict dependencies implementation, where it was installing all dependencies. Strict dependencies is supposed to require the entire dependencies tree. However, that fix didn't include running `pip check` to ensure that the venv doesn't have missing dependencies. I'll fix that.
