### ISSUE TITLE
Charmcraft crash when snap is used in /tmp directory

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#184]
Seen today:

```bash
$ pwd
/tmp/charm/ 

$ charmcraft init
charmcraft internal error! PermissionError: [Errno 13] Permission denied: '/var/lib/snapd/void' (full execution logs in /home/mark/snap/charmcraft/common/charmcraft-log-shi2xw2j)
```

I suspect this is snap confinement doing its job, and we just need to catch the permission error and handle it gracefully.

**Comment by facundobatista** [comment]
We'll go to the "classic" confinement mode in a near future, so this will no longer be a problem.

**Comment by facundobatista** [comment]
We're "classic" now.
