### ISSUE TITLE
Implement `charmcraft status <charmname>`

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#185]
It feels like it would be natural to be able to query the status of any given charm with:

`charmcraft status <charm>`

The results might depend on permissions, handling the situations where:

 - the charm name is not registered
 - the charm name is reserved
 - the charm name is registered but you don't have permission to see status
 - it's your charm and you can status if you want to

Note that `snapcraft status <snapname>` works as described.

**Comment by facundobatista** [comment]
We need support from the Store to implement this. Opened [this issue](https://bugs.launchpad.net/snapstore-server/+bug/1933250).

**Comment by sergiusens** [comment]
This is by Store design, the bug has a deeper explanation, fwiw, Snapcraft does not behave this way as the Store API behaves similarly.

Let's take the discussion to the bug report if needed and re-open this if the suggested path is to be taken.
