### ISSUE TITLE
Incorrect information in Charmhub for ARM64 variants of a charm

### ISSUE THREAD

**Issue by jameinel** [canonical/charmcraft#1853]
### Bug Description

As filed in https://bugs.launchpad.net/snapstore-server/+bug/2060271

the `github-runner` charm has both AMD64 and ARM64 builds. In particular rev 234 is an amd64 build, and 235 is an arm64 build.

When Juju goes to query charmhub, it gets a response that indicates that rev 234 supports both amd64 and arm64. I don't know whether this was a bug in how the data got recorded to charmhub (eg a charmcraft bug), or in how charmhub is using the information it currently has.
But across Juju, Charmhub, and Charmcraft we definitely have a bug around how the data is getting stored and then retrieved.

### To Reproduce

See bug 2060271, but:
```
juju --debug --logging-config "#charmhub=TRACE" download --arch arm64 github-runner --channel latest/beta
```
You can see that the response from Charmhub is saying:
```
        "bases": [
          {
            "architecture": "amd64",
            "channel": "22.04",
            "name": "ubuntu"
          },
          {
            "architecture": "arm64",
            "channel": "22.04",
            "name": "ubuntu"
          }
        ],
...
        "resources": [],
        "revision": 234,
        "summary": "Creates a group of self-hosted github runners.",
        "type": "charm",
        "version": "234"
```

However, revision 234 only supports amd64. (The revision 235 was the one that supported arm64.)

### Environment

One plausible explanation is that during upload of the arm64 build, something was incorrectly recorded in charmhub that made it think that rev 234 also supported arm.

### charmcraft.yaml

```shell
# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

type: charm
parts:
  charm:
    charm-python-packages:
      - setuptools  # for jinja2
    build-packages:
      - git  # for installing git source of pylxd 
      - libffi-dev  # for cffi
      - libssl-dev  # for cryptography
      - rust-all  # for cryptography
      - pkg-config # for cryptography
  scripts:
    plugin: dump
    source: scripts
    organize:
      build-lxd-image.sh: scripts/build-lxd-image.sh
      reactive_runner.py: scripts/reactive_runner.py
      repo_policy_compliance_service.py: scripts/repo_policy_compliance_service.py
    prime:
      - scripts/
bases:
  - build-on:
    - name: "ubuntu"
      channel: "22.04"
      architectures:
      - amd64
    run-on:
    - name: "ubuntu"
      channel: "22.04"
      architectures:
      - amd64
  - build-on:
    - name: "ubuntu"
      channel: "22.04"
      architectures:
      - arm64
    run-on:
    - name: "ubuntu"
      channel: "22.04"
      architectures:
      - arm64
```

### Relevant log output

```shell
I don't believe there is a relevant log for charmcraft.
```

**Comment by lengau** [comment]
Thanks for the report! This is a charmcraft bug, specifically #1783 . The manifest was being incorrectly built, using all possible architectures for the charm rather than the architecture for this specific build of the chram. Re-packing the charms with 3.1.2 or newer will create correct charms.
