### ISSUE TITLE
Support charmcraft.yaml, parts, pull and build behaviours

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#186]
Just a thought.

If some charms, even with the Python operator framework, are going to want to build code which they include in the charm, then we should reuse the snapcraft.yaml syntax to specify parts to be built. I'm not sure if we want to reuse stage and prime for subsetting the built output, but it might make sense.

In that world, the Python elements seem like an 'implicit part' right now.

A `charmcraft.yaml` would also provide a place to put the charmhub UUID for the charm, which would smooth over name changes, unless that will already be in metadata.yaml

**Comment by facundobatista** [comment]
Leaving this issue as the main issue for taking `charmcraft` to use the full lifecycle as in `snapcraft` (we're creating a library with this functionality that will be used from both projects).

I opened #216 for the "charm uuid" idea.

**Comment by facundobatista** [comment]
This is already in master.
