### ISSUE TITLE
Support `charmcraft info` for charmhub details for a charm name

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#187]
The `snap  info <foo>` command is very useful. I think it would make sense to have the same command in both juju and charmcraft. Am not sure what the plan is with the current `charm` command but I suspect most of that functionality will come to charmcraft. It might be nice to think about using the `charm` command to interact with charms in the model, potentially.

**Comment by facundobatista** [comment]
Getting the "info" for a charm/snap is more consumer side than developer side. We will talk with Juju people to check their plans about the `charm` utility and what would happen with the `charm show` functionality, if it will be absorbed by `juju` itself.

If not, we could bring it to the "developer side", but it will be something lacking in the consumer tooling.

**Comment by sergiusens** [comment]
I talked to @jameinel about this and from what we discussed juju will adopt this functionality.

**Comment by facundobatista** [comment]
I like it, we keep separated the developer/consumer sides, as in snapcraft/snap.
