### ISSUE TITLE
`pip check` linter

### ISSUE THREAD

**Issue by lengau** [canonical/charmcraft#1889]
### What needs to get done

Create a linter that checks that the venv is consistent using `pip check`

### Why it needs to get done

With strict dependencies, we want to give people a build-time error about missing dependencies rather than runtime.

**Comment by sergiusens** [comment]
Is this a Craft Application or Charmcraft analyze feature?

**Comment by lengau** [comment]
@sergiusens this would be a charmcraft linter (both in analyse and at the end of packing). I'm not sure how we could feasibly do this in craft-application.
