### ISSUE TITLE
Remove snapcraft references

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#189]
There are a number of vestigial snapcraft references in the charmcraft codebase.

HOWTO_SNAP.md
charmcraft/commands/store/store.py:            # N attempts (which should be big, as per snapcraft experience). Issue: #79.
charmcraft/commands/store/client.py:STORAGE_BASE_URL = 'https://storage.staging.snapcraftcontent.com'
tests/commands/test_store_client.py:        domain='snapcraft.io', domain_specified=True, domain_initial_dot=False, path='/',
tests/commands/test_store_client.py:    url = 'https://storage.staging.snapcraftcontent.com/unscanned-upload/'

Not sure if those latter references are meaningful.

**Comment by facundobatista** [comment]
Modules in the `charmcraft/commands/store/` (and corresponding tests) have "snapcraft" in the server URLs; we will talk with Store people about providing "more charmly" urls.

This is valid, though: `HOWTO_SNAP.md` is about snapping charmcraft itself.

**Comment by facundobatista** [comment]
The only current snapcraft reference is the server name to push blobs when uploading content, `https://storage.snapcraftcontent.com`. As there are no current plans from the Store to provide a new URL, I'm closing this as done.
