### ISSUE TITLE
`create-track` command

### ISSUE THREAD

**Issue by lengau** [canonical/charmcraft#1901]
### What needs to get done

Allow the user to create a track on Charmhub that meets the guardrails using this endpoint:

https://api.staging.charmhub.io/docs/default.html#create_tracks

### Why it needs to get done

User request: https://matrix.to/#/!GGqzbFAUQprdPgYYCM:ubuntu.com/$2rTS5bUb88C6KMC7npj-IOsifspe-scjNhCJKuYfKnA

**Comment by addyess** [comment]
Thanks @lengau,  some other details here. 

It would be super nice if this could work in snapcraft too.  

And even MORE exciting would be if i could use create tracks on a WHOLE BLOCK of things at once:


```sh
snapcraft create-track snap-a,snap-b,snap-c, ...snap-z --track 2.0
charmcraft create-track charm-a,charm-b,charm-c, ...charm-z --track 2.0
```

the current process is defined here
https://discourse.charmhub.io/t/how-to-create-a-track-for-your-charm/11102

I'll say the holy grail for this issue would be for the tools to just CREATE ON RELEASE if the track doesn't exist

```sh
snapcraft release my-snap 123 2.0/beta,latest/beta
charmcraft release my-charm --revision=123 --channel 2.0/beta --channel latest/beta
```

**Comment by addyess** [comment]
Hi, I'm still wishing this was a thing.  Maybe 2025?  Maybe a 2024 Christmas present?

**Comment by lengau** [comment]
@addyess it's a Christmas miracle! This is on my pulse for this pulse and I'm actively working on it right now!

![image](https://github.com/user-attachments/assets/9b1f16c7-050d-45a4-8fee-972c503b89de)
