### ISSUE TITLE
charmcraft logout doesn't tell you if you were logged out

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#191]
Seen with 0.6.0:

```
$ charmcraft logout
Credentials cleared.
$ charmcraft logout
Credentials cleared.
```

It would be better if the second logout said:

```
$ charmcraft logout
You were not logged in.
```

Though it would still exit successfully.

**Comment by facundobatista** [comment]
This was improved when we started using craft-store. At least 1.5 has this behaviour.
