### ISSUE TITLE
charmcraft login could list charms and statuses

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#192]
It would be nice if login provided a bit more information about the status of the account and charms managed by it, perhaps equivalent to snapcraft/charmcraft list.

For example:

```
$ charmcraft login
Logged in as 'conan'.
No charms registered.
```

Or 

```
$ charmcraft login
Logged in as 'conan'.

Name           Since       Visibility    Tracks    Notes
magmats        2016-10-07  public        0         -
asciinema      2017-01-16  public        3         -
babeld-dfgafl  2018-07-14  public        1         -
```

**Comment by facundobatista** [comment]
The `login` command is a rarely used one, as most commands have the "auto-login" feature (IOW, if you do `charmcraft status` and you're not logged in, it will ask you to login). So, for the rare case when you actually do `login`, probably means that you only want to do just that (maybe when automating charmcraft, for example, no point on having that extra query).
