### ISSUE TITLE
charmcraft revisions should take charm name directly

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#193]
It would be nice to say `charmcraft revisions <foo>` and have that just work! Using `--name` is unnecessarily awkward.

**Comment by sergiusens** [comment]
This is in sync with our tool alignment plan

**Comment by markshuttle** [comment]
Not sure if you are saying "yes" in which case great, or "no" in which case let's discuss :)

**Comment by sergiusens** [comment]
Hah, I can see how my reply can be confusing now, I am agreeing with you and the proposed change which aligns with the current UX for our other tools.

**Comment by facundobatista** [comment]
This is already released.
