### ISSUE TITLE
charmcraft upload should take a path directly

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#194]
It would be nicer to say:

```
$ charmcraft upload filename.charm
```

than the current

```
charmcraft upload --charm-file=filename.charm
```

In the same spirit, if we can actually use a metadata.yaml, then providing a path to the metadata.yaml, or a path to a directory with a metadata.yaml, would work. If there are multiple architecture builds in that directory in future then we could either try to upload them all or abort with a list and tell the user to be more specific.

**Comment by sergiusens** [comment]
This is in sync with our tool alignment plan

**Comment by facundobatista** [comment]
The way to specify the filepath is not longer an option. For the "automatically find the filepath" functionality I opened #312
