### ISSUE TITLE
`charmcraft init` would be better off with explicit directory name

### ISSUE THREAD

**Issue by markshuttle** [canonical/charmcraft#198]
The combination of --project-dir and --name in `charmcraft init` is rather awkward.

Could we make it that the directory is the only unqualified argument to init, and that --name is then an optional qualified argument along with --author?

So:

```
charmcraft init
charmcraft init directory
charmcraft init --name foo
charmcraft init directory --name foo
```

**Comment by sed-i** [comment]
I also was wondering if there's a reason for `charmcraft init --project-dir` not to auto create the project dir (as in `mkdir -p` / `os.makedirs(..., exist_ok=True)`).

Currently if the dir doesn't exist,
```console
charmcraft internal error! FileNotFoundError: [Errno 2] No such file or directory: ...
```

**Comment by jnsgruk** [comment]
I also find this a little awkward - to me a more sane default would be:

`charmcraft init test-charm`

Where that command would create the `test-charm` directory and populate it with the template

**Comment by facundobatista** [comment]
So, let's keep `--project-dir` for the standard way of pointing to project directories, and now that we have the fix to create the directory if not there, it shouldn't be surprising anymore. Let's see if in the future a similar need/situation arises.
