### ISSUE TITLE
Charmcraft snap fails to install due to a timeout on the configure hook

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/charmcraft#1987]
### Bug Description

Recently I've seen a flaky error appear on `snap install charmcraft`.
It seems that the `configure` step times out. It only occurs in CI so far, so it's probably due to resource constraints.

Example failure in CI: 
https://github.com/canonical/tempo-coordinator-k8s-operator/actions/runs/11814262043/job/32912967414?pr=62

Sometimes to make it go away it's enough to retry (a couple of times...).

### To Reproduce

`snap install charmcraft --classic --channel 3.x/candidate`

### Environment

Current runner version: '2.320.0'
Operating System
  Ubuntu
  [2](https://github.com/canonical/tempo-coordinator-k8s-operator/actions/runs/11814262043/job/32912967414?pr=62#step:1:2)4.04.1
  LTS
Runner Image
  Image: ubuntu-2[4](https://github.com/canonical/tempo-coordinator-k8s-operator/actions/runs/11814262043/job/32912967414?pr=62#step:1:4).04
  Version: 20241112.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20241112.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20241112.1

### charmcraft.yaml

```yaml
not applicable
```

### Relevant log output

```shell
/usr/bin/sudo snap install charmcraft --classic --channel 3.x/candidate
error: cannot perform the following tasks:
- Run configure hook of "charmcraft" snap if present (run hook "configure": <exceeded maximum runtime of 5m0s>)
Error: The process '/usr/bin/sudo' failed with exit code 1
Error: Error: The process '/usr/bin/sudo' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/canonical/charming-actions/934193396735701141a1decc3613818e412da606/dist/check-libraries/index.js:3950:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/canonical/charming-actions/934193396735701141a1decc3613818e412da606/dist/check-libraries/index.js:3933:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/canonical/charming-actions/934193396735701141a1decc3613818e412da606/dist/check-libraries/index.js:3827:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

**Comment by jnsgruk** [comment]
This was fixed in #1984 and should be released soon :)

**Comment by PietroPasotti** [comment]
not sure I see how it's related, but I hope you're right!

**Comment by jnsgruk** [comment]
The workaround for now is to `snap install lxd` before you install `charmcraft`

**Comment by PietroPasotti** [comment]
how does this explain the flaky behaviour? if it's missing lxd, how come it sometimes succeeds?

**Comment by PietroPasotti** [comment]
also it seems that my GH workflow already had a 

```
      - name: Setup LXD
        uses: canonical/setup-lxd@main
```

step right before the one that installs charmcraft. so either that step is b0rk or...?

**Comment by tigarmo** [comment]
@PietroPasotti according to the link you pasted (https://github.com/canonical/tempo-coordinator-k8s-operator/actions/runs/11814262043/job/32912967414?pr=62), the step that failed was "Check libs", which installs charmcraft but is separate from the job that sets up LXD (`prepare-itest-runs`)

**Comment by tigarmo** [comment]
> how does this explain the flaky behaviour? if it's missing lxd, how come it sometimes succeeds?

If LXD is missing, calling `lxc` will install the snap from the store. This can then fail sometimes depending on transient store issues.
