### ISSUE TITLE
GitHub Actions template in charmcraft

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/charmcraft#203]
In [graylog-operator we set up GitHub Actions](https://github.com/canonical/graylog-operator/blob/main/.github/workflows/python-package.yml) to have CI.
And I was wondering if it would be a good feature getting a functional CI template inside the directory structure when we run `charmcraft init`

**Pros**:

- Since a very important portion of the software repositories are created in GitHub, we would give the possibility of having continuous integration to the people who use charmcraft and manage the repository here, out of the box.
- Indirectly we encourage them to have automatic testing of their code, which is always good
- We help to standardize python versions, coding style, ways to build virtual environments, ways to run tests, etc

**Cons**:

- We would make charmcraft code a little bit more complex to support this functionality.
- A new file to be maintained 

**Considerations**:

- If the person who uses charmcraft to start writing their charm doesn't use github, will have an useless file in the repo.
- This template will not work in others repo/CI providers (gitlab, travis, etc)

I am not completely sure about this, on the one hand I think we could do it, but on the other hand I think
may be it would be good enough having the template in the documentation... This would however, encourage less use of CI.

What do you think @facundobatista @chipaca ?

**Comment by sergiusens** [comment]
This should probably be published as an action like we have for Snapcraft, two in fact, one for building and another for publishing.

**Comment by heitorPB** [comment]
IMO, this would be better off as documentation pages. There are too many git repo providers and CI systems, having support for them all would pollute the new charm project.

**Comment by sergiusens** [comment]
we decided not to do this
