### ISSUE TITLE
Built charm defaults to kubernetes cloud 

### ISSUE THREAD

**Issue by hatched** [canonical/charmcraft#237]
When you run `charmcraft init` it builds a charm with a default series being `kubernetes` but a default beginner Juju bootstrap is usually not.

A simple fix might be to expand the TODO items to include modifying the series array in the `metadata.yaml`. To hopefully avoid this error:

`ERROR cannot add application "my-charm": series "kubernetes" in a non container model not valid`

In the linked issue it suggests a few options for commands to build charms specifically for k8s but maybe the init command should be interactive instead.

Related: https://github.com/canonical/charmcraft/issues/111

**Comment by facundobatista** [comment]
We'll include a TODO for the developer to pay attention to `series` in `metadata.yaml`
