### ISSUE TITLE
`charmcraft build` will let you build a charm that won't deploy

### ISSUE THREAD

**Issue by mthaddon** [canonical/charmcraft#249]
As an example, if you modify the config.yaml of any charm to have a type of `integer` (as opposed to `int`) and then run charmcraft build it works fine and returns a 0 exit code. However, trying to deploy it will give (if the config item you edited was smtp_port):
```
ERROR invalid config: option "smtp_port" has unknown type "integer"
```

**Comment by facundobatista** [comment]
Hi @mthaddon !

We want to do several sanity checks at build time, we're collection those in issue #27 .

I added an item there regarding `config.yaml` (and `actions.yaml`) being valid YAMLs.

I'm closing this to track everything in the original issue.

Thanks!
