### ISSUE TITLE
pack README.md and require README.md in uploaded bundle

### ISSUE THREAD

**Issue by hmlanigan** [canonical/charmcraft#275]
Juju will deploy a local packed bundle without an README.md file.  However it will not deploy a bundle without a README.md file from charm hub.

Please require README.md to upload a bundle.

**Comment by hmlanigan** [comment]
charmcraft pack does not include a local README.md file when creating a bundle.zip file.

**Comment by hmlanigan** [comment]
Using the parts tag in charmcraft.yaml to include README.md was unsuccessful.

    type: bundle
    parts:
        bundle:
            prime: ["bundle.yaml", "README.md"]

**Comment by facundobatista** [comment]
It should include it with that config.

Can you please run `charmcraft` with `--verbose` and provide the resulting log lines? thanks!!

**Comment by hmlanigan** [comment]
hmmm... this time the README.md got added to the zip file as it was including in the ```prime``` list in the charmcraft.yaml.  However it is not a packed by default and a requirement for uploaded bundles which it needs be.

**Comment by jameinel** [comment]
I just ran into this. I successfully uploaded a bundle to the store, but juju would refuse to deploy it because its validation step checks to ensure there is a README.md.
As mentioned prime: can be used to workaround it, but that is just a gotcha waiting to happen for someone.
