### ISSUE TITLE
support `charmcraft export-login`

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#276]
Hello,

We are wondering how we can create a release system for our charms?

Can `charmcraft` gain `export-login` functionality similar to snapcraft?

Thanks

**Comment by sergiusens** [comment]
Yes, the export-login work done in Snapcraft (which recently gained integration with candid) will be brought into Charmcraft.

**Comment by jamesbeedy** [comment]
Hello,

How's it going? Just checking to see where this is at?

thanks

**Comment by facundobatista** [comment]
We'll be implementing all the functionality expressed in [this forum post](https://discourse.charmhub.io/t/how-to-authenticate-charmcraft-in-remote-environments/5313).

**Comment by heitorPB** [comment]
That's great! Do you have a target milestone for it?

**Comment by facundobatista** [comment]
This is released in v. 1.5.
