### ISSUE TITLE
`charmcraft build` failing if charm has manifest.yaml

### ISSUE THREAD

**Issue by mthaddon** [canonical/charmcraft#287]
I'm seeing the following error trying to build a charm with a manifest.yaml: https://pastebin.ubuntu.com/p/dzMkySj6dT/
```
$ snap info charmcraft
name:      charmcraft
summary:   The charming tool
publisher: Canonical✓
store-url: https://snapcraft.io/charmcraft
license:   Apache-2.0
description: |
  Charmcraft provides a streamlined, powerful, opinionated, and
  flexible tool to develop, package, and manage the lifecycle of Juju
  charm publication, focused particularly on charms written within the
  Operator Framework.
  
  It is still in heavy, initial development and so a lot is still To
  Be Done. However it is already useful, and already simplifies the
  life of the charmer.
commands:
  - charmcraft
snap-id:      gcqfpVCOUvmDuYT0Dh5PjdeGypSEzNdV
tracking:     latest/edge
refresh-date: today at 14:05 CEST
channels:
  latest/stable:    –                                       
  latest/candidate: –                                       
  latest/beta:      0.9.0             2021-03-11 (312) 10MB -
  latest/edge:      0.9.0+43.gfe2d065 2021-04-15 (357) 10MB -
installed:          0.9.0+43.gfe2d065            (357) 10MB -
```

**Comment by facundobatista** [comment]
@mthaddon you say that you have a `manifest.yaml` from *before*? We should support that and not crash as you're showing.

**Comment by jnsgruk** [comment]
@facundobatista we have been manually including essentially empty manifest.yaml files until now, but yeh it probably shouldn't crash! Maybe replace at charm build time and log a message during the build?

**Comment by facundobatista** [comment]
No, it should be too surprising that a file just changed (nobody reads the messages ;) ).

It should refuse to build, providing an error (just not crash).

**Comment by facundobatista** [comment]
This should be fixed already in master, as on one side we check for valid manifest.yaml, and also we build in clean dirs.
