### ISSUE TITLE
Use hardlinks in the build directory

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#29]
Actually, we should emulate `cp -al`:

- use hard links
- preserve permissions bits, mode, attributes, flags, etc
- preserve original symlinks (so "hooks" will look as they should, for example)
- do not dereference (never follow symbolic links in what we're linking to)
- copy directories recursively

As a side effect of this, we're able to allow symlinks in the zip file (not "copying contents" for everything!).

This will result in a build directory as close as possible to what would be found later when the package charm is unzipped.

**Comment by chipaca** [comment]
one complication this gains us is that we need to make sure we're not pulling in symlinks that point 'outside'
(can be done later as part of the sanity checks)

**Comment by facundobatista** [comment]
> (can be done later as part of the sanity checks)

I updated #27 to include this.

**Comment by jetpackdanger** [comment]
I imagine this will solve the current inability to directly deploy the "build" directory:

```
[agnew(charm-k8s-mattermost)] juju upgrade-charm --path ./build mattermost
ERROR cannot repackage charm: symlink "config.yaml" is absolute: "/home/paul/build/canonical/juju/mattermost/charm-k8s-mattermost/config.yaml"
[agnew(charm-k8s-mattermost)] _
```

which I am all for. :)

**Comment by jetpackdanger** [comment]
It just occurred to me to try the mattermost.charm file to "juju upgrade-charm", which works! Excellent.

**Comment by facundobatista** [comment]
Still missing "preserve permissions bits, mode, attributes, flags, etc" for directories
