### ISSUE TITLE
Not clear how to set "homepage" and "submit a bug" links via charmcraft

### ISSUE THREAD

**Issue by mthaddon** [canonical/charmcraft#309]
I've begun uploading charms to charmhub using charmcraft, and it's not clear to me how to set the "homepage" and "submit a bug" links that are imported from the charmstore for charms uploaded to there. For comparison, here's a charm uploaded directly to charmhub https://charmhub.io/nginx-ingress-integrator and here's one imported from the charmstore where it had those fields set using the "charm" tool https://charmhub.io/mattermost-charmers-mattermost.

**Comment by mthaddon** [comment]
I believe this is something that's set on charmhub itself now (via https://charmhub.io/charms once logged in). I'm not sure if it's intended to be able to set via charmcraft as well.

**Comment by facundobatista** [comment]
No plans to do that in charmcraft, exactly. Closing this, then. Thanks!
