### ISSUE TITLE
Support building in different platforms.

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#313]
Charmcraft should provide a way to build the charm in different platforms, through Multipass or LXC.

**Comment by heitorPB** [comment]
Would this allow a charm to be built for multiple operating systems? For example, our https://github.com/omnivector-solutions/slurm-charms can be deployed on CentOS7 and Ubuntu 20.04. But in Charmhub it only shows Ubuntu 20.04, even though we have both OS in the metadata files.

**Comment by facundobatista** [comment]
Yes, that's the idea.

But so far, to have your charm in Charmhub for CentOS, so far you will need to pack it in a CentOS machine. If you're packing it in a CentOS machine and still doesn't show using that OS in Charmhub, please open an issue and we'll help. 

Thanks!

**Comment by heitorPB** [comment]
Oh, nice!

> But so far, to have your charm in Charmhub for CentOS, so far you will need to pack it in a CentOS machine.

So, if I want to have a published charm for multiple OS, i need to release multiple versions? I mean, i have to pack it on CentOS and upload & release, then pack it on Ubuntu and upload & release, but in different tracks?

**Comment by facundobatista** [comment]
> So, if I want to have a published charm for multiple OS, i need to release multiple versions? I mean, i have to pack it on CentOS and upload & release, then pack it on Ubuntu and upload & release, but in different tracks?

Question: if you pack your charm in an Ubuntu machine, it should run in both Ubuntu and CentOS environments? (there may be cases where this works fine, according to what libraries you use, etc).

**Comment by facundobatista** [comment]
In any case, if your charm cannot work in both OSes, you will need to pack it twice.

So you would have a binary `.charm` file packed under Ubuntu, and other `.charm` file packed under CentOS. Then you will be able to upload both files to Charmhub, and release both to `latest/stable` (no need to have different tracks, as Charmhub differentiate them as they have different bases).

Then at deploy time, `juju` will select one or the other according to the system it's working on.

**Comment by heitorPB** [comment]
> Question: if you pack your charm in an Ubuntu machine, it should run in both Ubuntu and CentOS environments? (there may be cases where this works fine, according to what libraries you use, etc).

We have checks in the code to deal with differences in the operating systems, specially with the package manager (`apt` in Ubuntu and `yum` in CentOS) and file paths. We also test the code in both OSes in our CI. This way, the same code base can be used in both operating systems.

> In any case, if your charm cannot work in both OSes, you will need to pack it twice.

In our case, our charm does work in both OSes. So, we would like to pack, upload, and release only once.

In the charm metadata, we list both OSes, do you think it would be possible to have that information also in the final packed charm?

**Comment by facundobatista** [comment]
> In the charm metadata, we list both OSes, do you think it would be possible to have that information also in the final packed charm?

Not today. But when this issue is finished, you will be able to properly specify the bases in `charmcraft.yaml`, and Charmcraft will pack the charm once and the resulting output will be fit to run in both OSes.
