### ISSUE TITLE
Provide charmcraft installers for Windows and MacOS

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#314]
There should be a way to install `charmcraft` in Windows and MacOS.

**Comment by jameinel** [comment]
Wasn't this pip, or are you looking for prebuilt .app/.exe programs?

**Comment by sergiusens** [comment]
Homebrew for mac and an exe/msi for Windows, which wouldn't require a python setup as a pre-installation dependency.

We will mimic what we have for Snapcraft which to some extent was done for microk8s.
