### ISSUE TITLE
consider 'charmcraft list' vs 'charmcraft revisions'

### ISSUE THREAD

**Issue by jameinel** [canonical/charmcraft#318]
I'm not settled on it, but as I was trying to figure out what to publish, it was the name that came to my mind before revisions.

**Comment by facundobatista** [comment]
"list" what? we can think about listing charm names, or list bundles, or list resources, or list libraries...

**Comment by sergiusens** [comment]
To contrast, "snapcraft list" is equivalent to "charmcraft names"

**Comment by jameinel** [comment]
I'm fine closing this, just was the first command I reached for.
