### ISSUE TITLE
The charm tool should offer an initial skeleton

### ISSUE THREAD

**Issue by woutervb** [canonical/charmcraft#32]
As with many (new) frameworks that expose a lot of functionality, it's is easy to shoot oneself in the foot.
This is something that cannot be prevented, but I think that many 'beginners' mistakes could be prevented by providing some templates on how to realize certain functionality.

E.g. some helping code to create an operator framework 'project' with all links in place, using some templates for e.g. installing a snap, or a deb, or creating an interface to be reused.

**Comment by timClicks** [comment]
In lieu of `charmcraft init`, what is the recommended method for creating the 3 skeleton files needed to start, e.g. 

```plain
my-charm
├── config.yaml
├── metadata.yaml
├── requirements.txt
└── src/
    └── charm.py
```

**Comment by facundobatista** [comment]
Source of ideas: https://github.com/relaxdiego/operator-charm-template

**Comment by facundobatista** [comment]
> In lieu of `charmcraft init`, what is the recommended method for creating the 3 skeleton files needed to start, e.g.
> 
> ```
> my-charm
> ├── config.yaml
> ├── metadata.yaml
> ├── requirements.txt
> └── src/
>     └── charm.py
> ```

Hello @timClicks ! I'm not sure I understand your question... `config.yaml` and `metadata.yaml` are your regular charm's files, `src/charm.py` is the charm itself, and the `requirements.txt` is the file where you put your dependencies (e.g. `ops`).

**Comment by facundobatista** [comment]
Work for this has already landed. If we miss anything or want to improve current behaviour, let's open new issues for that. Thanks!
