### ISSUE TITLE
charmcraft release doesn't pay attention to resources

### ISSUE THREAD

**Issue by jameinel** [canonical/charmcraft#320]
I have a charm with an oci-image that I'm using for testing sidecar charms.

I did:
```
charmcraft build
charmcraft upload ./jam-k8s-api-sidecar-test.charm
charmcraft release -r 1 -c stable
```

And it happily let me do so. But now I have a sidecar charm that references a resource that doesn't exist.

**Comment by facundobatista** [comment]
Shouldn't this be caught by Charmhub, in the same way of thinking than it will not allow you to point to a wrong resource?

(note that for charmcraft itself, our current behaviour is to allow store-related commands to work even if you're not in the project, so `metadata.yaml` may not be available)

**Comment by facundobatista** [comment]
Also, that `release` command is strange, it should had gave you an error because you didn't specify the charm name.

**Comment by jameinel** [comment]
Sorry, I had typed it into the box from memory, looking at my bash history it was:
```
$ charmcraft release jam-k8s-api-sidecar-test -r 1 -c stable
```

**Comment by facundobatista** [comment]
After some talking, we agreed that this is better done Charmhub side. Opened [this issue](https://bugs.launchpad.net/snapstore-server/+bug/1951271) to track the request.
