### ISSUE TITLE
charmcraft init produces error charm for machine charms

### ISSUE THREAD

**Issue by erik78se** [canonical/charmcraft#328]
### description
I'm having a really bad experience from starting charming with charmcraft.

The default charm created as part of a "charmcraft init" seems defaulted to a kubernetes charm, which means that for anyone like me - still working on machine charms - the produced charm is broken from start and needs to be heavily modified to get running.

Consider new charmers. They will be stuck from start and giving up here.

The produced charm from "charmcraft init" should NEVER fail as this destroys the experience from anyone trying to get started on juju. 

**Please create a charm that works from start regardless if you are working on a K8 or machine charm.**

Since K8 charms and Machine charms are so different, it should be two different default charms created I guess. So, charmcraft init should really take that into consideration.

### version used
charmcraft               1.0.0                        403    latest/beta      canonical✓      -

**Comment by heitorPB** [comment]
`charmcraft init --vm` or `charmcraft init --k8s` would be nice to have.

**Comment by sergiusens** [comment]
This should no longer be an issue as the `series` keyword is no longer part of `metadata.yaml`.

Please re-open if still experiencing issues with the template generated by the latest charmcraft (1.2/1.3 at the time of this writing).

**Comment by heitorPB** [comment]
> This should no longer be an issue as the `series` keyword is no longer part of `metadata.yaml`.

I'm not sure that is the issue that @erik78se is reporting...

The issue is that `charmcraft init` only generates k8s charms. It is not helpful to create machine charms.
