### ISSUE TITLE
unregister command

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#331]
Hello,

I have registered a charm for the wrong username. I need to unregister the charm from my personal user and register it under a different username.

Is it possible for charmcraft to support some functionality that will allow a user to release the charm name registration?

Thanks

**Comment by facundobatista** [comment]
Opened [this bug](https://bugs.launchpad.net/snapstore-server/+bug/1945220) requesting for the functionality in Charmhub.

**Comment by facundobatista** [comment]
The API for this is [now in place](https://api.charmhub.io/docs/default.html#unregister_package)

**Comment by lengau** [comment]
Sorry, we overlooked closing this, but this has been in charmcraft for about a year now :-)
