### ISSUE TITLE
`charmcraft names` outputs to stderr instead of stdout

### ISSUE THREAD

**Issue by jameinel** [canonical/charmcraft#332]
This makes it hard to use with normal text processing lines (as reported by @jamesbeedy) (eg `charmcraft names | grep`).

I don't know if there is a standard process, but most command seem like progress messages/errors go to stderr but content output should go to stdout.

**Comment by jameinel** [comment]
Duplicate of #95

**Comment by facundobatista** [comment]
Yes, we're centralizing this in the other issue, let's close this, thanks!
