### ISSUE TITLE
Not able to register a charm name

### ISSUE THREAD

**Issue by alejdg** [canonical/charmcraft#337]
I'm trying to publish a charm called jenkins-agent but I'm stuck at trying to register the name.
```bash
$ charmcraft register jenkins-agent                                                                                                                                                
Store failure! Name 'jenkins-agent' is already registered [code: already-registered] (full execution logs in /[...]
$ charmcraft status jenkins-agent                                                                                                                                                 
Store failure! Name jenkins-agent not found in the charm namespace [code: resource-not-found] 
```
If I search for *jenkins-agent* in charmhub (https://charmhub.io/?q=jenkins-agent) the only result is jenkins-ci-charmers-jenkins-agent so I'm not sure what is happening. Does it exist already or not? If it does, why can't I see it anywhere?

Also, how do I upload a version of a charm under my own namespace like I would do with `charm push <charm-name> cs:~alejdg/<charm-name>`?

**Comment by jameinel** [comment]
For many names that we feel will be populate, they were reserved. If it is
a name that you want to use, reach out to 'roadmr' on mattermost and he can
assign the name to your user ID.

John
=:->

**Comment by alejdg** [comment]
@jameinel Thanks for the info! I'll do that.

However, it would be good to have a different message in that scenario where the charm does not exist yet.

**Comment by sergiusens** [comment]
We should have a different error code for _reserved_ and _registered_. It may be the case that the charm is already registered as well, just not with your account, this we can easily assess client side.

**Comment by facundobatista** [comment]
Opened [this bug](https://bugs.launchpad.net/snapstore-server/+bug/1945218) requesting the indicated functionality.

**Comment by facundobatista** [comment]
Closing this issue as the resolution is server side (tracked in the specified bug).
