### ISSUE TITLE
Make the O.S. to recognize .charm files

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#343]
It would be great if the operating system recognizes the `.charm` files in the same way it does with `.zip` files.

Maybe bash-completion files for the different tools should be updated?

**Comment by lengau** [comment]
Closing as out of scope. The only place I know where this is a problem is with specifically the bash completion for `unzip`. That should be considered an external bug there (they should be relying on the file's mime type, not its extension).
