### ISSUE TITLE
The `register` command is confusing

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#345]
We've seen several cases where people uses it to register names for bundles.

Probably it should be just replaced with `register-charm` (we already have `register-bundle`). We can deprecate the bare `register` and keep it for a couple of releases, for easier transition.

**Comment by sergiusens** [comment]
We should consult with design

**Comment by facundobatista** [comment]
After talking with design about this, the next steps would be to have only a `register` command with a mandatory option `--type` that will indicate the type of package that is being registered (`charm` or `bundle` for now, in the future this could grow).

The steps for this change are:

- add `--type` as optional

- give an error on plain `register`, so we'll stop the confusion; in this error we'll indicate to pass `--type=charm` explicitly.

- deprecate `register-bundle` (there's no risk of confusion here, and if we just remove the command we won't be able to provide a guiding message); in the deprecation message we'll indicate to use `register` with `--type=bundle`.

- one or two releases later, make `--type` option mandatory and remove `register-bundle`

**Comment by lengau** [comment]
Closing this as bundle registration is on its way out.
