### ISSUE TITLE
Charmcraft should gently retry the server operations when they fail with 5XX

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#353]
"Gentle" means to not add more burden to the server when it's already probably overloaded.

It could use a scheme where the first retry is fast (for real transient errors, to give the user a good experience), and quickly back off to more delayed attempts. Not too many, it's not good to hold the operation for ever to the user.

Proposed (in seconds): `[.1, .5, 1, 3, 5]`. If the server keeps failing after the total waitings (almost 10 seconds), just expose that failure.

**Comment by mthaddon** [comment]
I think this sounds like a good idea, but I also think we should figure out why we're getting so many failures, or at least make sure the teams on the other side of the failures are aware of them.

Anecdotally I would say I get failures from charmcraft commands that interact with charmhub about 30% of the time, which seems quite high.

**Comment by sergiusens** [comment]
This is a rather well known problem with the infra, snapd and snapcraft have measures to retry in their code base, once we strip out the http clients from Snapcraft, Charmcraft would get the retry logic for free (although not hard to reimplement here directly).

**Comment by sergiusens** [comment]
This will be solved once craft-store is integrated.

**Comment by facundobatista** [comment]
Integrated already!
