### ISSUE TITLE
Charmcraft release should be able to attach a resource during revision creation

### ISSUE THREAD

**Issue by alejdg** [canonical/charmcraft#354]
Charmcraft uses the same command to release a charm revision and to attach resources to a revision. However, `charmcraft release` doesn't allow for a resource to be attached in the moment the revision is being created, so it forces the user to run the same command twice:

```
$ charmcraft resource-revisions jenkins-agent-k8s jenkins-agent-image                                                                                                                             
Revision    Created at    Size
2           2021-05-25    143B
1           2021-05-25    143B

$ charmcraft status jenkins-agent-k8s
Track    Channel    Version    Revision
latest   stable     3          3
         candidate  ↑          ↑
         beta       ↑          ↑
         edge       2          2

$ charmcraft release jenkins-agent-k8s -r 3 -c edge --resource=jenkins-agent-image:2
Store failure! Resource 'jenkins-agent-image' is not valid for charm with id 'dsE0SLdKWW3RvK8fnJaqGCyNZkk6CRYo' and revision 3; Resource 'jenkins-agent-image' with revision 2 does not exist for charm with id 'dsE0SLdKWW3RvK8fnJaqGCyNZkk6CRYo' and revision 3 (full execution logs in /...)

$ charmcraft release jenkins-agent-k8s -r 3 -c edge
Revision 3 of charm 'jenkins-agent-k8s' released to edge

$ charmcraft release -r 3 -c edge jenkins-agent-k8s --resource jenkins-agent-image:2
Revision 3 of charm 'jenkins-agent-k8s' released to edge (attaching resources: 'jenkins-agent-image' r2)
```

**Comment by facundobatista** [comment]
Mmm... that should work. Maybe I'm not understanding the sequence, because it works in the test I did.

Is your case reproducible?

For clarity, I wrote the following sequence, let us understand where it diverges from your case:

**Situation:** A snap with a couple of resources, some revisions released...

    $ charmcraft status facundo-snappass-test
    Track    Channel    Version    Revision    Resources
    latest   stable     3          3           redis-image (r1), snappass-image (r1)
             candidate  ↑          ↑           ↑
             beta       ↑          ↑           ↑
             edge       ↑          ↑           ↑
    $ charmcraft revisions facundo-snappass-test
    Revision    Version    Created at    Status
    4           4          2021-06-03    approved
    3           3          2021-04-15    released
    2           2          2021-04-15    released
    1           1          2021-04-15    approved

Now I added one more resource to `metadata.yaml` (called `testres`), I build the charrm and upload it...

    $ charmcraft build
    Created 'facundo-snappass-test.charm'.
    $ charmcraft upload facundo-snappass-test.charm
    Revision 5 of 'facundo-snappass-test' created

Also upload the first revision of this new resource...
    
    $ charmcraft upload-resource facundo-snappass-test testres --filepath=~/temp/testfile.bin
    Revision 1 created of resource 'testres' for charm 'facundo-snappass-test'
    
All in order:

    $ charmcraft revisions facundo-snappass-test
    Revision    Version    Created at    Status
    5           5          2021-06-03    approved
    4           4          2021-06-03    approved
    3           3          2021-04-15    released
    2           2          2021-04-15    released
    1           1          2021-04-15    approved
    $ charmcraft resource-revisions facundo-snappass-test testres
    Revision    Created at    Size
    1           2021-06-03    627B

Now release the charm to edge, using this new resource:

    $ charmcraft -v release facundo-snappass-test --revision=5 --channel=edge --resource=testres:1
    Revision 5 of charm 'facundo-snappass-test' released to edge (attaching resources: 'testres' r1)

Do you spot the difference with your example? Or we're showing the same case?

Thanks!!!

**Comment by facundobatista** [comment]
Hello! Please reopen if you have more information about this issue, thanks!
