### ISSUE TITLE
Are the version and revision the same?

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#355]
<img width="841" alt="Screen Shot 2021-05-26 at 1 30 42 PM" src="https://user-images.githubusercontent.com/5590546/119726987-9ef7b280-be26-11eb-9bd3-182f292751c8.png">

Looking at the `charmcraft status slurmd` output I see the version and revision. Do we need both of these?

Thanks

**Comment by facundobatista** [comment]
They are not the same. 

The revision is a number, an integer, that grows in 1 every time a new charm is uploaded (assigned by Charmhub).

The version is controlled by the developer through the `version` file in the root directory of the charm. Whatever you put there, it will be used for the version of the charm (note that it's a text, so you can write something like `3.4.0alpha2`).

All that said, note that the version file is optional. If the uploaded charm has not a version file, the revision number will automatically be assigned as the version of the file.
