### ISSUE TITLE
How to "unrelease" a charm?

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#357]
I've released revision 5 of my charm to `candidate`, but I realized it was a mistake. Is there a way to "unrelease" it?

![slurmd](https://user-images.githubusercontent.com/13461702/119729734-628a7d80-be4b-11eb-8075-b06e9c347dac.png)

**Comment by facundobatista** [comment]
Hello, thanks for your question!

Charmhub does not have the "unrelease" concept.

You can release another revision in `candidate`, and revision 5 will stop being shown there. For example, if you previously had the revision 4 in that channel, releasing again revision 4 will bring you to the previous state.

In the future you would be able to *close* the channel, to not have any revision there (functionality to be implemented, see #232).

Thanks!

**Comment by facundobatista** [comment]
The `close` command is already in `master`, you can use it currently if you have the `charmcraft` from `edge`.

**Comment by heitorPB** [comment]
Thanks, @facundobatista!

I have a question: why do `charmcraft close` have a `--project-dir` option?

**Comment by facundobatista** [comment]
`--project-dir` is a global option, it works for all commands, and is useful to run charmcraft *not* in the location of each project.

So, you may do `charmcraft --project-dir=/var/projects/charm17/ close edge` and it will get the `charmcraft.yaml` of that project (in which, for example, you may override the default URLs in case of using an enterprise Charmhub, or staging...)
