### ISSUE TITLE
How to set the charm version?

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#358]
Using the operator framework, I can set the workload version, that is displayed with `juju status`, which is not the same as the version when `charmcraft pack` runs. I can use an arbitrary string for the workload version, but how do I set the charm version using `charmcraft`?

I see the `revision` is updated automatically on `charmcraft upload`, but it also automatically set my charm version to the same value.

**Comment by facundobatista** [comment]
Hello! To set the version of the charm, include it in a `version` named file.

**Comment by heitorPB** [comment]
Thanks!
