### ISSUE TITLE
feature request: charmcraft release=last-revision

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#368]
Maybe I am missing something, but this is my current workflow:

```bash
$ charmcraft upload slurmd.charm
Revision 12 of 'slurmd' created

$ charmcraft release slurmd --revision=12 --channel=edge
Revision 12 of charm 'slurmd' released to edge
```
For the `release` step, I need to manually type the revision number. I'd like to have something like `charmcraft release revision=last --channel=edge` to release the latest uploaded charm.

`revision=last` may not be the best CLI parameter, an alternative could be `revision=-1`.

But even better would be `charmcraft upload slurmd.charm --release --channel=edge`.

**Comment by facundobatista** [comment]
You can do that with almost the same syntax:

    charmcraft upload slurmd.charm --release=edge
