### ISSUE TITLE
Multiple files for packing a bundle is confusing

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#373]
Right now, if I want to upload a bundle to charmhub.io, I have to take a `bundle.yaml` file, add a `name` field (that's currently undocumented, see https://bugs.launchpad.net/juju/+bug/1931140), and then also create a separate `charmcraft.yaml` file that contains only the string `type: bundle`. It's kind of awkward and confusing to have those be two separate files.

I understand that we'll want `charmcraft.yaml` going forward as an analogue to `snapcraft.yaml`, and it will contain arbitrary build steps. So we don't want to get rid of `charmcraft.yaml`. However, would it be possible to have the contents of `bundle.yaml` contained in `charmcraft.yaml`? That would eliminate the extra file.

**Comment by sergiusens** [comment]
bundle.yaml is a legacy concept which is going to be replaced with stacks. charmcraft.yaml is all about the build-time definitions, we are not going with the Snapcraft model of having metadata and build rules in one file.

In essence you can actually construct bundle.yaml using the `parts` syntax, the default is to use a `bundle` plugin, but that can be overridden with whatever you want.
