### ISSUE TITLE
Handling multiple bundles in one repo

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#374]
Right now we've got 3 bundles defined in https://github.com/canonical/bundle-kubeflow:

- `bundle.yaml`
- `bundle-lite.yaml`
- `bundle-edge.yaml`

It's useful to keep these all in the same repo. However, it seems that `charmcraft pack` is hardcoded to look for `bundle.yaml`. How should we handle multiple bundles defined in the same repo?

**Comment by sed-i** [comment]
I have the same potential use case with https://github.com/canonical/lma-light-bundle

**Comment by sergiusens** [comment]
You can try and use multiple subdirectories which help you in having multiple charmcraft.yaml's for each bundle allowing you to be future proof.
