### ISSUE TITLE
`list-lib` should show you what command to run to fetch a library

### ISSUE THREAD

**Issue by mthaddon** [canonical/charmcraft#377]
Currently if you're looking for a library for a specific charm using charmcraft (e.g. `charmcraft list-lib nginx-ingress-integrator`) you get output like this:
```
Library name    API    Patch
ingress         0      9
```
To actually fetch that library you have to run `charmcraft fetch-lib charms.nginx_ingress_integrator.v0.ingress`. This isn't obvious from the `list-lib` command.

**Comment by sergiusens** [comment]
What we will do is show how to fetch listed libraries from list-lib's help.
