### ISSUE TITLE
Include all project files (whatever is present there)

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#39]
We're considering going the extra mile after including several well known files from the charm's project (`metadata.yaml`, `config.yaml`, etc).

We have several options:
- include **everything** present in the project's directory
- include everything except some specifics, like Juju does:
  - don't include `.git`, `.bzr`, etc... (or directly avoid including all hidden files/dirs)
  - don't include symlinks that are pointing to outside the project's directory
- include only very well known files (`metadata.yaml`, etc), and have a configuration for the developer to specify other files to be included.

Last option involves having some kind of "manifest", but note that first two options also would grow some kind of "block list" for the developer to specify something to *not* be included.

There's a compromise between both choices: if the developer needs to specify which files to be included, they may get caught by surprise, having built and published a charm lacking a file (broken!); if the developer needs to blocklist which files to be avoided in the package, they may got caught by surprise and have published a controversial file (security!).

**Comment by camille-rodriguez** [comment]
Hi @facundobatista , is there any update on this bug?

**Comment by jameinel** [comment]
https://discourse.juju.is/t/what-files-would-you-expect-charmcraft-build-copies-into-the-charm/3247

**Comment by facundobatista** [comment]
We took the decision of including everything except what Juju would ignore, to reduce the surprise factor between the tools behaviour and what the developer will expect when deploying.
