### ISSUE TITLE
Possibly change the default template to avoid some gotchas

### ISSUE THREAD

**Issue by evilnick** [canonical/charmcraft#393]
The current template works well as an example, but real charms can run into difficulties when the config changes something in the layer. The issues are pretty much expressed here:

https://github.com/canonical/operator/issues/553

I think it would be useful to adapt the pattern of the template to mitigate against these situations

**Comment by facundobatista** [comment]
Disclaimer: not fully understood all the conversation in the Operator's issue.

That said, which template modification are you suggesting? Thanks!

**Comment by evilnick** [comment]
This one I guess - https://github.com/canonical/charmcraft/blob/master/charmcraft/templates/init/src/charm.py.j2

The basic issue is the timing of the events (config_changed, pebble_ready) can lead to a confusing experience when someone tries to build a charm. Sorry, I don't have a proposal for what pattern would be better here, just that this one may lead to problems. 

@johnsca any suggestions?

**Comment by sergiusens** [comment]
I think the question is, what should the default template be for init?

**Comment by sergiusens** [comment]
We have decided to close this, feel free to take this to the forum where we are open to more brainstorming and once decided come back here and have an issue for.
