### ISSUE TITLE
`charmcraft info` command

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#404]
We need a command that users can execute to get details about a charm. Possibly `charmcraft info <charm-name>`?

Thoughts?

**Comment by jameinel** [comment]
There is 'juju info' though it currently needs a running controller to
determine what charm store you are connected to. But I think something like
'charmcraft info' would, indeed, be useful.

**Comment by facundobatista** [comment]
Closing this as duplicate of #187, where we took the decision of `juju` providing this functionality, which is also aligned to the behaviours of `snapcraft`/`snap`.

Maybe you could comment in the other bug why the functionality should be duplicated in two different tools, benefits, etc. Thanks!
