### ISSUE TITLE
Adopt SDI library as an official part of charmcraft

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#421]
This library was created to make it easy to create schema-based interfaces that charms can use to related to one another:

https://github.com/canonical/serialized-data-interface

Would it be possible to support this library officially in charmcraft? There's two things that come to mind as meaning "officially supported":

- Automatically download the schema at build time, instead of the existing behavior of downloading the schema at run time
  - This is one is pretty straightforward. [See here](https://github.com/canonical/mlmd-operator/blob/master/metadata.yaml#L16-L20) for an existing example of how the schema is specified in `metadata.yaml`. Right now the Python code in SDI parses `metadata.yaml` at runtime to figure out what to download, but `charmcraft build` could just automatically handle this.
- Charm store support
  - This one is more complex. At a minimum, it would involve being able to upload schemas to the charm store, so that charm authors can reference a schema as
        
        schema: grpc
        
    instead of
    
        schema: https://raw.githubusercontent.com/canonical/operator-schemas/master/grpc.yaml
        
    as the current state of things is fairly ugly without charm store support. This would probably also include things like `charmcraft show-interface grpc`, which would show the currently-defined schema.

**Comment by sergiusens** [comment]
As discussed we are going to close it and create fallout items from the result of a proposed spec the encompasses the complete story end to end.

**Comment by sed-i** [comment]
> create fallout items from the result of a proposed spec

Could you please link to the "fallout items"?
I am looking now into documenting my relation interfaces and was wondering if I should take the schema route at this point.

**Comment by knkski** [comment]
@sed-i See here for overall proposal:

https://docs.google.com/document/d/1mpG_t9cB0CDWzpUlTRK5_eED-abLY5Z4wxEIdgqLtCM/

Apart from that, you can easily use the SDI library independently of that proposal (which just adds better integration with charmcraft). See here for an example of where we're using it in the Kubeflow bundle:

https://github.com/canonical/kubeflow-volumes-operator/blob/master/metadata.yaml#L14-L18
https://github.com/canonical/kubeflow-volumes-operator/blob/master/src/charm.py#L26-L35
