### ISSUE TITLE
build and run on centos 7/8 in charmcraft.yaml

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#430]
Hello,

We have charms that support centos7 and ubuntu 20.04. Looking at how to build our charms using the new pattern/functionality we can't see how to do so for centos. Is it possible that we have an example of how a `charmcraft.yaml` might look for OS other then ubuntu?

Thank you

**Comment by erik78se** [comment]
Same here for other charms.

**Comment by facundobatista** [comment]
Thanks @heitorPB for the proposed solution for this.

FTR, I will make explicit what that configuration does, and close this issue. If you need a different behaviour and don't know how to achieve it, feel free to reopen this. Also check [the full docs](https://discourse.charmhub.io/t/charmcraft-bases-provider-support/4713) for a comprehensive explanation of how this works.

So, in the proposed solution `charmcraft` will build the charm in a Ubuntu 20.04 environment, and will flag that the charm can run BOTH on Ubuntu 20.04 and CentOS 7, always on `amd64`.

Regards,
