### ISSUE TITLE
Output path changed with charmcraft 1.1.0

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#434]
`charmcraft pack --project-dir foo/` used to build the charm and save the output in the current directory. With Charmcraft 1.1.0, `charmcraft pack` saves the charmfile in the `project-dir` folder.

Is it possible to revert this the the previous behavior? That is, save the charm file in the current directory, instead of in the dir specified with `--project-dir`?

**Comment by facundobatista** [comment]
This is a regression, will fix ASAP.
