### ISSUE TITLE
[docs] how to run charmcraft as part of a CI?

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#439]
Hello,

We use GitHub actions to pack our charms, deploy in a test environment to run some final tests, and publish it to latest/edge.

but with the recent changes, our CI is broken we are struggling to build the charms in there. Could you provide an example of how to:
- pack the charms as part of CI
- publish to a channel automatically

Thanks!

**Comment by sergiusens** [comment]
We can create a documentation and a github action as we have for Snapcraft (build and publish actions)

**Comment by facundobatista** [comment]
That said, if your CI is broken with latest changes and can't fix it, open other issue so we can help you! Thanks.

**Comment by sergiusens** [comment]
There are actions and ways to do this now, closing but feel free to open if something is missed
