### ISSUE TITLE
charmcraft upload foo.charm --release=edge gives internal error

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#456]
```bash
$ charmcraft upload slurmd.charm --release=edge
Revision 21 of 'slurmd' created
charmcraft internal error! TypeError: release() missing 1 required positional argument: 'resources' (full execution logs in /home/h/snap/charmcraft/common/charmcraft-log-61cp9xr8)
```

This command used to work, but it is not working anymore. Am I missing something? Documentation says nothing about `resources`.

```
$ snap info charmcraft
name:      charmcraft
summary:   The charming tool
publisher: Canonical✓
store-url: https://snapcraft.io/charmcraft
license:   Apache-2.0
description: |
  Charmcraft enables charm creators to build, publish, and manage charmed operators for
  Kubernetes, metal and virtual machines.
commands:
  - charmcraft
snap-id:      gcqfpVCOUvmDuYT0Dh5PjdeGypSEzNdV
tracking:     latest/edge
refresh-date: today at 09:38 -03
channels:
  latest/stable:    1.1.1             2021-07-15 (513) 51MB classic
  latest/candidate: 1.1.1             2021-07-09 (513) 51MB classic
  latest/beta:      1.1.1             2021-07-09 (513) 51MB classic
  latest/edge:      1.1.0+72.gccc10f3 2021-07-20 (534) 51MB classic
installed:          1.1.0+72.gccc10f3            (534) 51MB classic
```

**Comment by facundobatista** [comment]
Thanks @heitorPB per reporting this. It's indeed a regression, I proposed a PR to fix it and we'll release 1.1.2 with the fix as soon it's approved.

The initial release will be to `candidate` channel, then to `stable` after some verification. May I ask you to use charmcraft from `candidate` channel? this way you will have the fix sooner, on one hand, but also we would enjoy your testing and issues reports before we hit to stable.

Thanks!

**Comment by heitorPB** [comment]
Thanks for fixing it @facundobatista !

It will be released to `edge` as well? That is what I've been using, but I can switch to `candidate` if needed.

**Comment by facundobatista** [comment]
Every commit in `master` goes to `edge`, so you will have it there sooner than from `candidate`. If you're using `edge` stay there, then, the earlier the broad testing, the better! Thanks!
