### ISSUE TITLE
charmcraft upload errors out with exit status 0

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#467]
```bash
$ charmcraft pack
Created '/mlflow-operator/mlflow.zip'.

$ charmcraft upload mlflow.zip --release=edge
Upload failed with status 'rejected':
- review-error: Missing required file: metadata.yaml

$ echo $?
0
```

This makes it difficult to include in a CD job, as you can't actually tell if you've uploaded a bundle successfully or not

**Comment by facundobatista** [comment]
Hello @knkski!

We have two situations here. One is that the `upload` command is not setting `retcode=1`. I opened #478 for this.

The second situation is that Charmhub is complaining that your bundle doesn't have `metadata.yaml`, which is a file required form charms (not bundles).

So, I'm closing this issue, letting #478 for the retcode detail, but please reopen or ping me directly for the bundle/charm confusion. Thanks!!
