### ISSUE TITLE
Support automated git sha tagging of charm builds

### ISSUE THREAD

**Issue by balbirthomas** [canonical/charmcraft#469]
# Introduction
When bugs occurs with charms, say some charm in Charmhub it would be useful for the developer to know which github sha that charm was built from. This will allow the developer to make a custom/debug build of that same version of the charm in order to reproduce and debug the issue.

## Suggestions

It would be nice if `charmcraft pack` included the git sha that was used to build the charm, for example in the `versions` file.

**Comment by heitorPB** [comment]
We use the command `git describe --tags --dirty` to generate the `version` file as part of our build process. We use `Makefile` to simplify our life, one example is https://github.com/omnivector-solutions/charm-prometheus-node-exporter/blob/main/Makefile

**Comment by sergiusens** [comment]
dup #37
