### ISSUE TITLE
initialization order means early log lines can be lost

### ISSUE THREAD

**Issue by chipaca** [canonical/charmcraft#48]
When running with `--verbose`, everything that is logged before `Dispatcher.run` is never seen by the user. To see them they'd have to also set `DEBUG` in the environ.
This feels like a bug to me. Parsing of the command line should be the first thing done, or at least early enough that the debugger doesn't need to change modes after the fact.

**Comment by jameinel** [comment]
Agreed. In Juju agents start in DEBUG until they have gotten confirmation of a lower log level. That isnt quite as appropriate for a user tool. I wonder about putting everything into the log file early on?

**Comment by facundobatista** [comment]
Reopening, as we still need to remove this DEBUG flag.
