### ISSUE TITLE
Stop using jujuignore file to ignore files

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#481]
The preferred way of controlling what's inside the built charm is now the `prime` list in the config, as it's specified [here](https://discourse.charmhub.io/t/charm-packing-will-not-include-all-files-by-default-anymore/4924).

**Comment by heitorPB** [comment]
What does this mean?

Charmcraft will ignore the `.jujuignore` file? Will it display a _deprecated warning_?

**Comment by facundobatista** [comment]
We talked about this, and we changed plans. We'll keep this for now.

In the future it may mutate to make it configurable more in line with the other charmcraft config, but for now we'll keep this.
