### ISSUE TITLE
Please include the LICENSE in the final charm by default

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#482]
Removing the LICENSE file when packing and distributing charms does not sound like a good idea to me.

This file holds essential information on usage and distribution of charm files.

**Comment by sed-i** [comment]
BTW, isn't `icon.svg` a well known file as well?

**Comment by heitorPB** [comment]
On Wed, 04 Aug 2021 11:55:32 -0700
sed-i ***@***.***> wrote:

> BTW, isn't `icon.svg` a well known file as well?
> 

I think that is the file used in Charmhub, right? not having it in the
final charm would be another huge loss...
