### ISSUE TITLE
Add a linter to verify the "run on" targets

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#486]
There should be linter that finishes in error if there is any "run on" in config's `bases` with a value different than the following options (name / channel):
- ubuntu 18.04
- ubuntu 20.04
- centos 7
- centos 8

**Comment by heitorPB** [comment]
How do add support for a new linux distro? Let's say I want my new `foo` charm to also run on [Rocky](https://rockylinux.org/), what would I need to do?

**Comment by facundobatista** [comment]
You'd need to request for it [in the forum](https://discourse.charmhub.io/), as the limitation is not in the developer/building side, but in the user/deployment one, with Juju.

**Comment by heitorPB** [comment]
Is there any plans to also validate the CPU architecture? The only acceptable ones should be the architectures that juju can run.

**Comment by facundobatista** [comment]
Verifying architectures too is a good idea.

Note we should do this as a linter and not as a "hard config validation" because the developer can always ignore the linter (e.g. for the situation of testing non-standard platforms).

**Comment by lengau** [comment]
This has been implemented as a side-effect of other changes
