### ISSUE TITLE
charmcraft should log where it's logging to, and when the logfile is removed

### ISSUE THREAD

**Issue by chipaca** [canonical/charmcraft#49]
When running with `--verbose` it would be useful to see two things:
1. an early log about where things are being logged, e.g.

       2020-06-24 10:52:17,239  charmcraft                     DEBUG    Logging to /tmp/charmcraft-log-22sbe9rb

2. a towards-the-end log when and if that logfile is removed, e.g.

       2020-06-24 10:56:11,640  charmcraft                     DEBUG    Logfile removed.

(It was in fixing this that I noticed #48).

**Comment by facundobatista** [comment]
This functionality will be provided by the `craft-cli` library.

Note however that logfiles will not be removed at the end (see #53), so it's just adding a line at the beginning... and we need to even reconsider this, if logfiles will go to a known place.

**Comment by facundobatista** [comment]
Integrated already!
