### ISSUE TITLE
pack fails with ERROR: Cannot find command 'git'

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#490]
I installed charmcraft 1.2.0 on a new system, and `charmcraft pack` fails with "Cannot find command 'git'" (see attach).
I then `snap refresh` to stable, and pack works. Then `snap refresh` back to candidate, and pack suddenly works.
In other words, when refreshing from a previous version, pack works; when installing a fresh 1.2.0, pack fails.

[charmcraft-no-git.log](https://github.com/canonical/charmcraft/files/6957566/charmcraft-no-git.log)

**Comment by sergiusens** [comment]
We will create a how-to to solve this and check requirements.txt for VCS usage to error out appropriately with missing dependencies and how to solve it.

**Comment by sed-i** [comment]
I get the same issue now with 1.2.1, which was auto-refreshed by snap from 1.2.0.

**Comment by cmatsuoka** [comment]
Extra tools required by the charm build process should now be listed under the part's `build-packages` entry:
```
part:
  charm:
    build-packages: [git]
```
This should also work for any other VCS supported by pip, or any external tool needed by the charm build process.

**Comment by heitorPB** [comment]
I added this snippet in my `charmcraft.yaml` and I got this error:
```bash
Bad charmcraft.yaml content:
- extra field 'part' not permitted in top-level configuration (full execution logs in '/home/h/snap/charmcraft/common/charmcraft-log-p6jg20m_')
```

Using charmacraft `1.2+36.g1b85509`

**Comment by cmatsuoka** [comment]
Updated: `part` was a typo, it's `parts`.

**Comment by cmatsuoka** [comment]
@sed-i @heitorPB This should address the issue, please reopen if the problem persists.
