### ISSUE TITLE
charmcraft Pack is not Working

### ISSUE THREAD

**Issue by Vaishalinicky** [canonical/charmcraft#497]
Hello Team,

charmcraft pack command is not working. PFB error and all the required details

root@microk8s2:/home/vagrant/abc# charmcraft version
1.1.1
root@microk8s2:/home/vagrant/abc# whoami
root
root@microk8s2:/home/vagrant/abc# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
root@microk8s2:/home/vagrant/abc# lxd --version
4.0.7
root@microk8s2:/home/vagrant/abc# charmcraft pack
Packing charm 'abc_ubuntu-20.04-amd64.charm'...
charmcraft internal error! PermissionError: [Errno 13] Permission denied: '/root/project/build' (full execution logs in /tmp/charmcraft.log)
Failed to build charm for bases index '0'. (full execution logs in '/root/snap/charmcraft/common/charmcraft-log-1bcbfndd')
root@microk8s2:/home/vagrant/abc# more /root/snap/charmcraft/common/charmcraft-log-1bcbfndd
2021-08-16 08:41:10,548  charmcraft.guard                         DEBUG    Starting charmcraft version 1.1.1
mm 2021-08-16 08:41:47,994  charmcraft.commands.build                DEBUG    Building charm in '/root/project/build'
mm 2021-08-16 08:41:47,994  charmcraft                               ERROR    charmcraft internal error! PermissionError: [Errno 13] Permission denied: '/roo
t/project/build' (full execution logs in /tmp/charmcraft.log)
mm 2021-08-16 08:41:47,997  charmcraft.guard                         ERROR
Traceback (most recent call last):
  File "/snap/charmcraft/x4/lib/charmcraft/main.py", line 362, in main
    dispatcher.run()
  File "/snap/charmcraft/x4/lib/charmcraft/main.py", line 348, in run
    self.command.run(self.parsed_args)
  File "/snap/charmcraft/x4/lib/charmcraft/commands/pack.py", line 132, in run
    self._pack_charm(parsed_args)
  File "/snap/charmcraft/x4/lib/charmcraft/commands/pack.py", line 161, in _pack_charm
    builder.run(parsed_args.bases_index)
  File "/snap/charmcraft/x4/lib/charmcraft/commands/build.py", line 220, in run
    charm_name = self.build_charm(bases_config)
  File "/snap/charmcraft/x4/lib/charmcraft/commands/build.py", line 165, in build_charm
    self.buildpath.mkdir()
  File "/snap/charmcraft/x4/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/root/project/build'

2021-08-16 08:41:48,696  craft_providers.lxd.lxc                  DEBUG    Executing on host: lxc --project charmcraft config device show local:charmcraft-ab
c-777845-0-0-amd64
2021-08-16 08:41:48,884  craft_providers.lxd.lxc                  DEBUG    Executing on host: lxc --project charmcraft config device remove local:charmcraft-
abc-777845-0-0-amd64 disk-/root/project
2021-08-16 08:41:49,229  craft_providers.lxd.lxc                  DEBUG    Executing on host: lxc --project charmcraft stop local:charmcraft-abc-777845-0-0-a
md64
2021-08-16 08:41:51,615  charmcraft                               ERROR    Failed to build charm for bases index '0'. (full execution logs in '/root/snap/cha
rmcraft/common/charmcraft-log-1bcbfndd')

Let me know if you need more from my end.

**Comment by cjp256** [comment]
Can you provide the output for:
```
lxc --project charmcraft start local:charmcraft-abc-777845-0-0-a
lxc --project charmcraft exec local:charmcraft-abc-777845-0-0-a -- ls -al /root/project

findmnt -T /home/vagrant/abc
ls -al /home/vagrant/abc
```

We have a change that was just merged that may address this issue for you.  If you want to give it a shot, it should be published to the edge channel within an hour or so:
`sudo snap refresh charmcraft --edge`

**Comment by Vaishalinicky** [comment]
vagrant@microk8s2:~/abcd$ sudo lxc --project charmcraft start local:charmcraft-abc-777845-0-0-a
Error: not found
vagrant@microk8s2:~/abcd$ sudo lxc --project charmcraft exec local:charmcraft-abc-777845-0-0-a -- ls -al /root/project
Error: not found
vagrant@microk8s2:~/abcd$
vagrant@microk8s2:~/abcd$ findmnt -T /home/vagrant/abcd
TARGET SOURCE    FSTYPE OPTIONS
/      /dev/sda1 ext4   rw,relatime
vagrant@microk8s2:~/abcd$
vagrant@microk8s2:~/abcd$ ls -al /home/vagrant/abc
total 72
drwxrwxr-x 4 vagrant microk8s  4096 Aug 17 08:32 .
drwxr-xr-x 9 vagrant vagrant   4096 Aug 17 10:54 ..
-rw-r--r-- 1 root    root        99 Aug 17 08:32 .flake8
-rw-r--r-- 1 root    root        55 Aug 17 08:32 .gitignore
-rw-r--r-- 1 root    root        24 Aug 17 08:32 .jujuignore
-rw-r--r-- 1 root    root     11358 Aug 17 08:32 LICENSE
-rw-r--r-- 1 root    root       510 Aug 17 08:32 README.md
-rw-r--r-- 1 root    root       473 Aug 17 08:32 actions.yaml
-rw-r--r-- 1 root    root       233 Aug 17 08:32 charmcraft.yaml
-rw-r--r-- 1 root    root       420 Aug 17 08:32 config.yaml
-rw-r--r-- 1 root    root       521 Aug 17 08:32 metadata.yaml
-rw-r--r-- 1 root    root        36 Aug 17 08:32 requirements-dev.txt
-rw-r--r-- 1 root    root        13 Aug 17 08:32 requirements.txt
-rwxr-xr-x 1 root    root       345 Aug 17 08:32 run_tests
drwxr-xr-x 2 root    root      4096 Aug 17 08:32 src
drwxr-xr-x 2 root    root      4096 Aug 17 08:32 tests
vagrant@microk8s2:~/abcd$

response of all the commands 

vagrant@microk8s2:~/abcd$ sudo snap refresh charmcraft --edge
charmcraft (edge) 1.2+41.gae4647f from Canonical✓ refreshed
vagrant@microk8s2:~/abcd$ sudo charmcraft pack
Packing charm 'abcd_ubuntu-20.04-amd64.charm'...

charmcraft pack is taking too much time

**Comment by cjp256** [comment]
Ah, can you run Charmcraft pack without sudo?

I'd also suggest running `sudo charmcraft clean; charmcraft clean` first to reset things

**Comment by cjp256** [comment]
The project on the host looks like its owned by root, but probably should be owned by the user (vagrant).  Before retrying the pack command, consider fixing this `chown -R vagrant:vagrant /home/vagrant/abcd`

**Comment by Vaishalinicky** [comment]
xecution logs in /home/vagrant/snap/charmcraft/common/charmcraft-log-j0ob2x0l)
vagrant@microk8s2:~/abcd$ charmcraft pack
LXD requires additional permissions.
Ensure that the user is in the 'lxd' group. (full execution logs in '/home/vagrant/snap/charmcraft/common/charmcraft-log-kugl868g')
vagrant@microk8s2:~/abcd$ sudo adduser $USER lxd
Adding user `vagrant' to group `lxd' ...
Adding user vagrant to group lxd
Done.
vagrant@microk8s2:~/abcd$ newgrp lxd
vagrant@microk8s2:~/abcd$ charmcraft clean
Cleaned project 'abcd'.
vagrant@microk8s2:~/abcd$ ls
LICENSE  README.md  actions.yaml  charmcraft.yaml  config.yaml  metadata.yaml  requirements-dev.txt  requirements.txt  run_tests  src  tests
vagrant@microk8s2:~/abcd$ charmcraft pack
Packing charm 'abcd_ubuntu-20.04-amd64.charm'...

Created 'abcd_ubuntu-20.04-amd64.charm'.
vagrant@microk8s2:~/abcd$

Thank you charmcraft is started working now

**Comment by Vaishalinicky** [comment]
Below are the steps which are working perfectly fine (used below steps on 2 VM as well).

@cjp256 Thank you for you help :)

1. sudo snap remove lxd
2. sudo snap install lxd
3. sudo apt-get update && sudo apt-get upgrade -y
4. snap install snapcraft --classic
5. sudo snap install microk8s --classic 
6. sudo usermod -a -G microk8s $USER
7. su - $USER
8. microk8s status --wait-ready
9. microk8s.kubectl get all --all-namespaces
10. microk8s.enable dns storage ingress
11. sudo snap install juju --classic
12. juju bootstrap microk8s micro
13. juju clouds
14. sudo snap install charmcraft --classic
15. sudo snap refresh charmcraft --edge
16. sudo adduser $USER lxd
17. newgrp lxd
18. lxd init

- Would you like to use LXD clustering? (yes/no) [default=no]: no
-   Do you want to configure a new storage pool? (yes/no) [default=yes]: yes
-   Name of the new storage pool [default=default]: default
-   Name of the storage backend to use (btrfs, dir, lvm, zfs, ceph) [default=zfs]: zfs
-   Create a new ZFS pool? (yes/no) [default=yes]: yes
-   Would you like to use an existing empty block device (e.g. a disk or partition)? (yes/no) [default=no]: no
-   Size in GB of the new loop device (1GB minimum) [default=7GB]: 1GB
-   Would you like to connect to a MAAS server? (yes/no) [default=no]: no
-   Would you like to create a new local network bridge? (yes/no) [default=yes]: yes
-   What should the new bridge be called? [default=lxdbr0]: lxdbr0
-   What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: auto
-   What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: auto
-   Would you like the LXD server to be available over the network? (yes/no) [default=no]: no
-   Would you like stale cached images to be updated automatically? (yes/no) [default=yes] yes
-   Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: no

19. mkdir hello-world
20. cd hello-world
21. charmcraft init
22. charmcraft pack
