### ISSUE TITLE
Build a charmed failed

### ISSUE THREAD

**Issue by hanjl93** [canonical/charmcraft#506]
build a charmed failed.
root@admin:~/my-new-charm# charmcraft build
Failed to show profile 'default'.
* Command that failed: 'lxc --project default profile show local:default'
* Command exit code: 1
* Command standard error output: b'Error: unknown flag: --project\n' (full execution logs in '/root/snap/charmcraft/common/charmcraft-log-5c69smtr')
![Snipaste_2021-08-25_10-26-22](https://user-images.githubusercontent.com/89497692/130716059-105918a2-1d56-4569-a633-8e6dd4f7a737.png)

**Comment by cjp256** [comment]
Can you run `lxc version`?  I expect that you may need a newer LXD that has project support :-( Though it should be checking that it is 4.0+, I'll have to look into it.

**Comment by cmatsuoka** [comment]
Can you run `charmcraft pack --verbose` and post the first ten or so lines of the output? I expect the following error to appear:
```
2021-09-06 20:22:20,022  charmcraft            ERROR    LXD '3.0.3' does not meet the minimum required version '4.0'.
```

**Comment by sergiusens** [comment]
Can you please provide the output of the following command:

- cat /etc/os-release
- which lxc
- dpkg -S lxd-client
- snap info lxd

Thanks in advance

**Comment by lengau** [comment]
Please reopen if you're still facing this issue.
