### ISSUE TITLE
Ensure credentials are stored in a safe place

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#52]
We need to revisit where the credentials are stored. So far we put them in a file in user's config directory, we may move them later to a wallet or whatever. 

We must do this before setting the default backend to production.

**Comment by facundobatista** [comment]
The idea was to have the current "file in disk" with better permissions flags for 0.4.0, that's done, this should be moved to 0.5.0.

**Comment by facundobatista** [comment]
Regarding using a better backend than the filesystem, what about [keyring](https://pypi.org/project/keyring/)?

**Comment by chipaca** [comment]
Given the additional complexities of supporting keyring inside the snap, and #122 ensures the credentials are stored with restrictive permissions, we're calling this Done; at least for now.
