### ISSUE TITLE
Destructive mode does not allow for building charms in parallel

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#526]
I have a bundle with two charms. When I try to build both charms at the same time with `--destructive-mode`, I get this error:

    charmcraft internal error! LockFailedException: Failed to lock directory /home/knkski/snap/charmcraft/common/cache/charmcraft/stage-packages/var/lib/apt/lists/: E:Could not get lock /home/knkski/snap/charmcraft/common/cache/charmcraft/stage-packages/var/lib/apt/lists/lock. It is held by process 128762 (python3) (full execution logs in /home/knkski/snap/charmcraft/common/charmcraft-log-30ipuxhg)

It looks like `charmcraft` is not using the charm's name anywhere in that path, so building multiple charms in parallel simply won't work atm, as they'll fight over the lock.

I realize this is called `--destructive-mode`, but if one accepts that risk then there doesn't seem to be any reason not to namespace the building process/directories by charm name.

**Comment by sergiusens** [comment]
This should be fixed in charmcraft once we integrate craft-parts 1.0.1

**Comment by cmatsuoka** [comment]
This should be fixed in Charmcraft 1.3.0.
