### ISSUE TITLE
Keep all latest logs

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#53]
This are several small changes:
- start storing the logs in user's cache directory
- don't remove the log file when charmcraft ends
- keep latest N log files (`RotatingFileHandler`)
- have a parameter in the config about that N

**Comment by facundobatista** [comment]
When running from the snap, there's no need to move them to the user's cache dir, as it's inside snap dirs.

**Comment by facundobatista** [comment]
This functionality will be provided by the `craft-cli` library.

Two modifications to the original plan, though:
- don't use the user's "cache" dir, but the "log" dir
- don't have an option for `N` (as all logs depend on the tool, and config is per-project)

**Comment by cmatsuoka** [comment]
+1 for plan. Agree with changes, logs are not cached files.

**Comment by facundobatista** [comment]
Integrated already!
