### ISSUE TITLE
Change in file permissions not picked up by craft-parts

### ISSUE THREAD

**Issue by mmanciop** [canonical/charmcraft#534]
`craft-parts` does not seem to pick up changes in file permissions as dirty state. I had a charm in which the `charm.py` was not marked as `+x`, which caused it to not work when deployed. When fixing the file permissions in my repository, it took a `charmcraft clean` before the built charm would work properly.

**Comment by cmatsuoka** [comment]
This should be addressed in craft-parts 1.0.2.

**Comment by facundobatista** [comment]
> This should be addressed in craft-parts 1.0.2.

Any particular reason we cannot upgrade `charmcraft` to use `craft-parts 1.0.2`?

**Comment by cmatsuoka** [comment]
> Any particular reason we cannot upgrade `charmcraft` to use `craft-parts 1.0.2`?

We'll do that as soon as 1.0.2 is available. That should take a few more days, since 1.0.1 has just been tagged.
