### ISSUE TITLE
progress (percent complete) indication of upload-resource is buggy

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#536]
During upload-resource I noticed that:
1. occasionally the percentage is above 100%
2. a stray `%7%` is present (see screenshot)

![Screenshot from 2021-09-13 09-14-16](https://user-images.githubusercontent.com/82407168/133090373-de49700a-bbca-4551-acc3-43d9e675e985.png)

**Comment by facundobatista** [comment]
Hello! Thanks for the report!

We have plans to replace this progress-showing functionality (we're currently working on that). We're tracking this #381, so I'm closing this issue as it's kind of duplicate from that.

Thanks again!
