### ISSUE TITLE
init template: replace run_tests, requirements-dev etc. with tox.ini and pyproject.toml

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#542]
Recently all o11y charms moved to tox and we find it quite handy.
For examples: https://github.com/canonical/karma-operator

**Comment by jnsgruk** [comment]
I think we should pursue this. Most, if not all of the charms I've seen in heavy use at Canonical have moved to this model. Bundling `tox` is possibly a little heavy for very simple charms, but would allow us to include examples of unit/integration tests in the default template, which might encourage good behaviours.

I also like the idea of including `flake8` and `black` configs in `pyproject.toml` to help make adhering to style guidelines easier. We should probably discuss a sane set of options, though.

**Comment by sergiusens** [comment]
Well if we are all in on this, I am also going to propose pyright and mypy

**Comment by facundobatista** [comment]
I don't like growing the basic template for a super complex way of building charms. I think we should be very opinionated on how people structure their charms and provide functionality to use Juju, but not on how people writes Python.

The original idea of `charmcraft init` was to help a "charm newbie" to start a charm with a minimum set of usable options. We may want to reconvert this for creating a super complex and opinionated charm with a lot of small tools around it, I'm -0 to that. 

Particularly, I'm -1 to start mimicking specific teams consensus that may variate through time. How does this help people starting to write charms?

Maybe the "very specific" or "advanced" needs would be better fulfilled starting those charms from a project's template in Github or a similar tool, and not `charmcraft init`?

**Comment by jnsgruk** [comment]
I'm with you to an extent. I think we should keep the template relatively simple, and hence I think mypy could be a step too far.

That said, I do think we should give people a clear idea of how to prepare their charm code for people to collaborate effectively, and how to test across environments.

This change could be a first step to including some basic integration tests that use the pytest/libjuju stuff, which set the tone immediately about how to effectively conduct proper testing?

I think we're close to being able to publish a sort of "style guide" or set of conventions for charms, and including some tooling to help people to adhere to that is not a bad thing imo.

**Comment by facundobatista** [comment]
This already landed as part of the "multiple profiles in init command" work.
