### ISSUE TITLE
Add a `charmcraft init` template for machine charms

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#568]
Currently, `charmcraft init` creates a k8s template for the charms. Pretty much all of our systems run machine charms, and we have to always start from scratch.

What about having also a machine charm template? And a toggle switch: `charmcraft init --vm` or `charmcraft init --k8s`?

(There was a related discussion in https://github.com/canonical/charmcraft/issues/328)

**Comment by PietroPasotti** [comment]
This also came up in a community workshop earlier today, there is definitely interest in this, and it looks like a low-hanging fruit :)
