### ISSUE TITLE
Output not formatted correctly for upload-resource

### ISSUE THREAD

**Issue by dstathis** [canonical/charmcraft#600]
```
$ charmcraft upload-resource cassandra-k8s cassandra-image --image cassandra:3.11
Remote image not found, uploading from local registry.
Uploading.. 91.55%%7%
```

**Comment by facundobatista** [comment]
Hello! A couple of weeks ago we landed an improvement to this progress indication and others (now you should see a nice progress bar), so this old behaviour is no longer present in the codebase. Thanks!
