### ISSUE TITLE
Add linter to check charm's categories

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#607]
According to https://github.com/canonical-web-and-design/charmhub.io/issues/1171#issuecomment-976579707, CharmHub uses the `categories` keyword in the metadata to enable the search filters on the search page.

It would be nice if Charmcraft could validate the categories in the `metadata.yaml`.

The list of CharmHub categories today:

```
ai-ml
big-data
cloud
containers
databases
logging-tracing
monitoring
networking
security
storage
```

I think `charmcraft` should issue a warning (not an error) if the charm contains a category outside this list. What are your thoughts on this?

**Comment by facundobatista** [comment]
I like it. Why a warning and not an error? if you're using an invalid category we should refuse to build.

**Comment by heitorPB** [comment]
> Why a warning and not an error? if you're using an invalid category we should refuse to build.

Imagine there's a new category in Charmhub and I want to use it today. If `charmcraft` errors out and refuses to build, my charm can't use it, I will have to wait until another release of the tool. The CI will not work either. If it were a warning, `charmcraft` would complain and I would be able to use the new category.

But this metadata about the charms was removed from `metadata.yaml`, we should have it in a discourse post instead: https://discourse.charmhub.io/t/charm-visibility-on-charmhub-tags-categories/5380


So, in the end: charmcraft should issue a warning that the charms contain `tags` and/or `categories` when linting?

**Comment by facundobatista** [comment]
Oh, I see, now "categories" and "tags" are deprecated from the `metadata.yaml` file (tags concept is just gone, and categories are set in Charmhub, as that discourse post explains).

So yes, probably `charmcraft` should check this. Again, why a warning and not a regular linter?

**Comment by heitorPB** [comment]
> Again, why a warning and not a regular linter?

Because it is not an error in the charm code. Also, imagine if you are packing an "old" charm, that still has `tags` and `categories` and suddenly `charmcraft` starts erroring because some _metadata_ was deprecated. That would be frustrating and probably would affect many CI systems out there.

Maybe issue a warning now, and in 6 months move that to an error? That would give some time for people to update their charms.

**Comment by facundobatista** [comment]
FTR, these fields are already gone from the [metadata reference](https://juju.is/docs/sdk/metadata-reference).

**Comment by facundobatista** [comment]
Closing this as we're not planning to verify the Juju's YAML files contents (we may revisit this later if schemas are provided for those).
