### ISSUE TITLE
`charmcraft upload-resource` Uploading percentage with a wrong format

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/charmcraft#611]
When using `charmcraft upload-resource` I can see a bad percentage format:

```bash
$ charmcraft upload-resource grafana-agent-k8s agent-image --image=f7554c099f25
Remote image not found, uploading from local registry.
Uploading.. 48.14%%6%
```

**Comment by facundobatista** [comment]
Hello! A couple of weeks ago we landed an improvement to this progress indication and others (now you should see a nice progress bar), so this old behaviour is no longer present in the codebase. Thanks!
