### ISSUE TITLE
Cannot pack charms with long names

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#629]
```
* Command output: b'Creating charmcraft-finos-legend-gitlab-integrator-k8s-24120086-0-0-amd64\n'
* Command standard error output: b'Error: Invalid instance name: Name must be 1-63 characters long\n' 
```

If we detect it's too long, we could shorten the name, but adding a hash of the full name, to avoid collisions.

To workaround this just shorten the name of the charm manually.

**Comment by heitorPB** [comment]
Why the name is limited to 63 characters?

**Comment by facundobatista** [comment]
It's a [limitation in LXC](https://linuxcontainers.org/lxd/docs/master/instances/).

**Comment by jameinel** [comment]
Certainly Juju has run into those sorts of issues in the past (systemd also
doesn't like long names). I believe we went with a trick where

```
if len(name) > X {
  name = name[:X-6]
  name += '-' hash(name)[5]
}
```

So for anything with a name too long we just truncate the tail and add on a
hash. It isn't perfect, but it does mean a different name maps to a
different name and doesn't overflow character limits.

**Comment by cmatsuoka** [comment]
The current naming format is `charmcraft-<project name>-<project path inode>-<bases index>-<build-on index>`. We could retain the project name, truncated to a size, and add a hash of the path and the base parameters. The initial `charmcraft-` isn't even needed because Charmcraft uses a separate lxd project for its instances.

**Comment by facundobatista** [comment]
But LXD is not the only backend, what about Multipass? In any case, I'm +0 to remove the initial `charmcraft`.

**Comment by facundobatista** [comment]
This is already fixed.
