### ISSUE TITLE
Similar functionality to "charm pull"

### ISSUE THREAD

**Issue by DomFleischmann** [canonical/charmcraft#630]
With the `charm` tool it was possible to pull a specific charm from the charmstore. This was very useful to identify exactly which charm was published.

Currently, there is no feature like it in charmcraft and it would be very useful.

**Comment by jameinel** [comment]
There is currently 'juju download charm' that does address some of this
functionality, though I think it should also be built into the 'charmcraft'
tool.
(Also, I think 'juju download' is clumsy to use when doing it without an
active controller.)

**Comment by facundobatista** [comment]
Dup of #344.
