### ISSUE TITLE
Improve error message when there is an issue with config.yaml

### ISSUE THREAD

**Issue by dstathis** [canonical/charmcraft#636]
Currently, if you have an issue with `config.yaml`, the error message tells you what is wrong and provides [this link](https://juju.is/docs/sdk/charmcraft-analyze#heading--juju-config) to information about the linter. That page is rather unhelpful because it just lists the reasons why the linter can fail, but, you have already been given the reason in the error line. I recommend providing [this link](https://discourse.charmhub.io/t/creating-config-yaml-and-configuring-charms/1039) instead as it gives information about how to format your `config.yaml` correctly.

**Comment by facundobatista** [comment]
The current link is correct, as all linters/attributes should link to the explanation on *why they fail*. 

OTOH, the link you're providing is super useful too, and it's a good idea to provide a path for the user to end there. For that, I improved the linter documentation itself so it ends up pointing there.

Thanks!!
