### ISSUE TITLE
`charmcraft pack` fails with error writing to lxd unix socket

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#660]
All of a sudden `charmcraft pack` fails with

```
invoke-rc.d: policy-rc.d denied execution of restart.
Error: write unix @->/var/snap/lxd/common/lxd/unix.socket: i/o timeout
```

After `charmcraft clean` I was able to `pack` successfully.

[charmcraft.log](https://github.com/canonical/charmcraft/files/8029237/charmcraft.log)

**Comment by facundobatista** [comment]
Did it happen again? To detect if it's an LXC problem, when you have this error, would you please check if you can enter into the container manually? Thanks!

**Comment by sed-i** [comment]
This did not happen again since. Closing.
