### ISSUE TITLE
Deprecate the `build` command

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#664]
We have `pack` for a lot of time now. It's time to officially add a deprecation notice when `build` is used.

**Comment by dstathis** [comment]
> Hi, Instead of deprecating the `charmcraft build` command would it be possible to re-purpose it as a lighter and faster "developer build" that just does a `pip install` and `zip` as `charmcraft` once used too. The benefit of providing developers a "rapid build" command is that it shortens their iteration times for "edit and rebuild" during development. Of course it could be clearly documented that all final testing must be done with `charmcraft pack`.

+1 to this suggestion. The workflow has gotten a lot slower since charmcraft changed to using containers and a faster build option would be really useful.

**Comment by facundobatista** [comment]
Nop, `build` will have other meaning in the future, can't stay. For having faster builds, we will improve speed of current packing, if possible. There are no plans of having a "half packing" where stuff is not built in containers and compiling everything.

**Comment by facundobatista** [comment]
It's already deprecated in v1.5.
