### ISSUE TITLE
Transition from "prime" to "charm-files" for including files

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#666]
To craft-parts, the prime keyword is a file filter mechanism. This keyword is being overloaded in craft-parts. The proposal is to make the application (Charmcraft) re-write the prime keyword to a new one to pass to the plugin (charm-files) and loading craft-parts with the default prime filter, with the possibility of allowing both to co-exist.

**Comment by lengau** [comment]
In charmcraft 3.0 this has removed altogether. The prime keyword now behaves as other craft-parts based apps do, and documentation has been added for migrating to use the dump plugin: https://juju.is/docs/sdk/include-extra-files-in-a-charm

This raised #1609, which is going to be taken care of by detecting use of the `prime` keyword and warning the user.
