### ISSUE TITLE
`charmcraft` should allow setting versions for `juju status`

### ISSUE THREAD

**Issue by rbarry82** [canonical/charmcraft#669]
I went diving into the source again, and `charmcraft` is carefully whitelisting files in `charmcraft/commands/build.py`. This makes creating a `version` file from git during build time (but before `.jujuignore` is processed) impractical, since it would not be present at build time.

`charmcraft pack` should result in a meaningful version in `juju status`. It would be great if `juju` did this on its own, or Operator Framework handled `set_workload_version` automagically, but we can cross that bridge...

We'd also love to have a way to keep a manifest generated from `pip freeze` assuming there's requirements, but pretty much the same scenario

------------------------

As an aside, it would be great to have `CONTRIBUTING.md` updated again. The default doesn't appear to have any effect, and it required me to set `CHARMCRAFT_MANAGED_MODE=1`, then run with sudo, since otherwise the lxd container didn't run from the checked-out source.

If this is expected behavior, please document it. If there's a good way to inject this into the LXD/multipass providers, please document it.

**Comment by facundobatista** [comment]
There are two aspects here about "version" and "juju status"

- if you want to include specific files other than the mandatory ones, you need to specify them in `charmcraft.yaml`, using `parts.charm.prime`, see [the reference here](https://juju.is/docs/sdk/charmcraft-config).
- for `charmcraft pack` to autogenerate a version file, we have [other issue opened](#37).

Regarding having `pip freeze` output stored in the manifest, this is unrelated to this issue, please open a different one.

Regarding `CONTRIBUTING.md`, yes, `CHARMCRAFT_MANAGED_MODE=1` need is no longer there, so we could remove it from the file. That said, I didn't understand where you need to run what with "sudo". Could you please elaborate? Thanks!

**Comment by rbarry82** [comment]
It’s the opposite, actually — `CONTRIBUTING.md` did not appear to he sufficient for a development workflow without `CHARMCRAFT_MANAGED_MODE`, changes made to `charmcraft` weren’t reflected in the actual build step inside the provisioner, which doesn’t appear to include any environment variables either. Using `sudo` with managed mode to work on the development machine at least ran with the changes in the patch. 

It’s not clear what a development workflow should be with provisioners.

**Comment by facundobatista** [comment]
> changes made to `charmcraft` weren’t reflected in the actual build step inside the provisioner,

Ah, I understand your problem now. We should expand `CONTRIBUTING.md` to explain that problem. Opened #695 for this.

I'd like to close this GitHub issue, as it covers several different details which are addressed in other issues; just let me know if there is any leftover. Thanks!
