### ISSUE TITLE
Validate internet is available after generating an instance in "providers"

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#673]
As packing most surely would need internet access, and if it's not available will produce weird errors during pulling/building. Note that this needs [support from craft-providers](https://github.com/canonical/craft-providers/issues/87).

**Comment by dstathis** [comment]
We may want to mention docker incompatibility and link to [this](https://linuxcontainers.org/lxd/docs/master/howto/network_bridge_firewalld/#prevent-issues-with-lxd-and-docker) in the error message.

**Comment by lengau** [comment]
Fixed upstream in craft-providers
