### ISSUE TITLE
charmcraft build fails with LXD version 

### ISSUE THREAD

**Issue by psreekrishnan** [canonical/charmcraft#676]
I use 'charm' cli to build and publish the Juju charms. But recently that became unreachable and recommended using "charmcraft" for the same.
I see an error while doing charmcraft build or pack, on LXD version. Is that is the requirement for building the charm?
"_LXD '3.0.3' does not meet the minimum required version '4.0'._"

**Comment by facundobatista** [comment]
To pack charms the default behaviour is that charmcraft will create an LXD instance and install stuff there and do all the packing. For this you need a modern LXD, yes,

Alternatively, you could pack passing the `--destructive-mode` option, and `charmcraft` will do all the work in your system.
