### ISSUE TITLE
Add a --name parameter to upload command (to use a different name than the specified in metadata.yaml)

### ISSUE THREAD

**Issue by morphis** [canonical/charmcraft#681]
With the recent transition of the old charm store to charmhub all charm uploads now need to be handled. In our case charms are available to our customers through the old charm store URLs (e.g. `cs:~anbox-charmers/ams`) and the `metadata.yaml` file includes `name: ams`. Migration to charmhub flat names is in progress but we will have customers using the charm store URLs for some more time and need to make sure we continue to support them.

The problem now is that charmcraft forces us to rename the charm in `metadata.yaml` when we want to upload it to charmhub. WIth the import `cs:~anbox-charmers/ams` became `anbox-charmers-ams` on charmhub but the charm still contains `name: anbox` in `metadata.yaml` and has to continue to do so for backward compatibility and as we plan to move it in the near future to the flat name `ams` on charmhub.

The problem is specifically in the implementation of the upload command where it derives name to upload to on charmhub from the name set in `metadata.yaml` (see https://github.com/canonical/charmcraft/blob/main/charmcraft/commands/store/__init__.py#L64) which will fails as in our case it will derive `ams` rather than `anbox-charmers-ams` and with that will upload to the wrong charm or fail if permissions to upload to the `ams` are not given.

To workaround we added a `--name` argument to the upload command in a custom charmcraft we're using for the time being which allows to upload to a specific charm on charmhub which doesn't match the name specified in `metadata.yaml`.

It would be great if we can get this solved in charmcraft proper.

**Comment by mthaddon** [comment]
We'd also be very interested in this, would be a great modification to be able to do `charmcraft upload --name myname-mycharm ${filename}` to allow easier uploads to a personal namespace without having to change `metadata.yaml`.

**Comment by morphis** [comment]
The workaround I was talking about is https://paste.ubuntu.com/p/CZbgbt679h/

**Comment by morphis** [comment]
@facundobatista Do you see any problem with adding the `--name` argument? If not, I can provide a PR to get that added.

**Comment by morphis** [comment]
@facundobatista I went ahead and implemented this now. Let me know if there is any feedback
