### ISSUE TITLE
charmcraft upload reports 504, but charm was uploaded

### ISSUE THREAD

**Issue by mthaddon** [canonical/charmcraft#688]
I just uploaded a new version of the nginx-ingress-integrator charm. On upload it reported a 504, but the charm had indeed been uploaded and I could release it fine.

Details are here https://pastebin.ubuntu.com/p/WZpxnyzRSh/.

**Comment by facundobatista** [comment]
It looks the server finished internally all the needed work but failed to answer back in a timely manner. We got a 504. As we can't really know what happened inside the server, all we can do is show that 504... or we could improve this?

**Comment by lengau** [comment]
This should be resolved. Please reopen if you get this again.
