### ISSUE TITLE
Charms packed using the reactive plugin shows dirty version

### ISSUE THREAD

**Issue by hloeung** [canonical/charmcraft#693]
Hi,

My charmcraft.yaml is available at https://git.launchpad.net/smtp-relay-charm/tree/charmcraft.yaml

When charms are built using `charmcraft pack`, the `version` generated adds the `-dirty` tag. This is because the reactive plugin removes charmcraft.yaml before calling `charm-tools`'s `charm build`. This is in https://github.com/canonical/charmcraft/blob/main/charmcraft/reactive_plugin.py#L147

`charm-tools`'s `charm build` uses `git describe --dirty --always` per https://github.com/juju/charm-tools/blob/master/charmtools/build/tactics.py#L1348

    [hloeung@dharkan build]$ pwd
    /home/hloeung/tmp/smtp-relay/build/parts/charm/build
    [hloeung@dharkan build]$ git describe --dirty --always
    3e81ffa-dirty

**Comment by facundobatista** [comment]
Do you know if there is a way for telling `charm` to *ignore* `charmcraft.yaml`? Because the alternative is leave it there, but would be a problem for it to be inside charms?

**Comment by hloeung** [comment]
I don't know of a way for telling `charm` to ignore `charmcraft.yaml`. But I think the alternative to leaving it there works, it wouldn't be a problem for any of the charms, in fact, charms leave things like Makefiles, pytest.ini, tox.ini, and wheelhouse.txt among other things.

**Comment by hloeung** [comment]
Or if we wanted to, could call `zip` with `--exclude charmcraft.yaml` so it's not included in the .charm zipfile?

**Comment by facundobatista** [comment]
We will stop removing it.
