### ISSUE TITLE
charmcraft pack should have a 'quick' option to override certain folders in an existing .charm file

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/charmcraft#694]
Use case:
I am debugging a charm.py file (nothing else changes, no new hooks are added),
currently charmcraft pack takes a few minutes. 

Would be nice if I could do something like
```
charmcraft pack --override /path/to/myCharm.charm /path/to/src /path/to/lib /path/to/src/charm.py
```

As a workaround I currently use a script that unpacks the charm, overwrites charm.py, repacks the charm.

**Comment by facundobatista** [comment]
Hello! The first time you call `pack` it creates a lot of infrastructure. The second time you call `pack` it should be way, way faster. Under a minute.

Of course, if you call `clean` in the middle, all that infrastructure needs to be created again.

If a second `pack` takes more than a minute, would you please add call it with `--verbose` and provide us the logs?

Thank you!

**Comment by rwcarlsen** [comment]
It is indeed a bit faster after an initial packing.  But it still seems like we should be able to do much better than order 10s of seconds.  If I `charmcraft pack` two times in a row (e.g. if I can't remember if I changed anything) I really wish it didn't take ~30 seconds for a simple charm each time on my pretty speedy laptop.  Surely there are some smart hashing/caching, etc. things that can be done to make it take on the order of a couple seconds instead.

Relatedly, I'm curious what is the particular reasoning behind packing via an lxd container vs. just doing things directly?

**Comment by PietroPasotti** [comment]
This issue is also a duplicate: https://github.com/canonical/charmcraft/issues/731
