### ISSUE TITLE
Allow for modifications to build environment of "charmcraft build" to accomodate for extra prerequisites

### ISSUE THREAD

**Issue by Vultaire** [canonical/charmcraft#696]
I hit an issue with jinja2 recently while writing an operator-based charm.  If I specify jinja2 as a dependency, I end up hitting a build bug since jinja2 is pulled via sources rather than via wheels.

I was able to reproduce this in a normal venv, and thus suspected a jinja2 issue, filing this bug: https://github.com/pallets/jinja/issues/1610

However, the jinja2 team came back saying that the setuptools and pip I'm using are too old to work with the latest jinja2.  Sure enough, when I upgraded those 2 packages first, I could install jinja2 cleanly.  ...I seem to be able to work around this by using an older jinja2, but this is obviously less than ideal.

Based on this experience, I'd like to suggest: can we have a flag so that we can pull and use the latest versions of setuptools/pip prior to installing the packages from requirements.txt?  Or alternatively, can we allow for multiple ```pip install``` stages, allowing us to force ordering of package installs in the case of badly-behaved packages?  (The latter is more just an idea; the former is the real need that I think needs to be addressed.)

**Comment by facundobatista** [comment]
The mechanism is already in place: you can specify some python packages to be installed before the actual requirements. This is an easy way to solve your situation, see [this forum post](https://discourse.charmhub.io/t/install-or-update-python-packages-before-packing-a-charm/5158) for more information.

Thanks!
