### ISSUE TITLE
`fetch-lib --dry-run`

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#702]
It would be handy for CI if there was a way to determine if charm libs are up to date, without making changes to the worktree, for example:

`charmcraft fetch-lib --dry-run`

I would add it right away to a tox testenv.

**Comment by facundobatista** [comment]
We'll have a linter that does this verification (see #417). You could run `analyze` on the directory (after #642 is done), and check if everything is up to date or not.

Would that be enough? Thanks!

**Comment by sed-i** [comment]
Ideally it should be possible to get separate answers to individual questions.
But I guess a non-zero return value from analyze should fail a tox env anyway right?
Then yeah it should do it.

**Comment by facundobatista** [comment]
Fantastic, thanks! So I'm closing this, as all functionality will be provided when #417 is finished. Thanks!!
