### ISSUE TITLE
Allow to specify a specific "part" in the `clean` command

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#704]
Currently, `charmcraft clean` will clean everything related to the project.

But if the project is composed by several "parts" (in the charmcraft.yaml building lifecycle sense) there is the possibility of needing to clean one part but not others (that may be potentially expensive to re-work).

We can leave `charmcraft clean` to clean all parts, and `charmcraft clean PART-NAME` for a specific one. IOW, PART-NAME would be optional.

**Comment by lengau** [comment]
Fixed with craft-application migration
