### ISSUE TITLE
Metadata v1 charms should be classified as invalid

### ISSUE THREAD

**Issue by SimonRichardson** [canonical/charmcraft#732]
Now the charmstore cut-over has happened, all charms using `charmcraft pack` or `charmcraft build` should not allow metadata v1. Instead, all new deployments should use metadata v2. This will help deprecate the old style by using the new charmcraft tool and we can in the future remove metadata v1 charms that haven't been updated.

**Comment by lengau** [comment]
Since Charmcraft is now writing the metadata field for most charms, I think this is no longer necessary.
