### ISSUE TITLE
Provide 22.04 as a building base

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#742]
Charmcraft should allow 22.04 as a base for building charms. 

Note this is blocked by having [the base available in Craft Providers](https://github.com/canonical/craft-providers/issues/108).

**Comment by PietroPasotti** [comment]
This might address some of the pain in #738 since hopefully 22.04 comes with a newer setuptools

**Comment by facundobatista** [comment]
> This might address some of the pain in #738 since hopefully 22.04 comes with a newer setuptools

Yes!

**Comment by facundobatista** [comment]
Fixed now.
