### ISSUE TITLE
`charmcraft pack` for existing environment does not remove files that have been deleted

### ISSUE THREAD

**Issue by ca-scribner** [canonical/charmcraft#746]
### What happened
If you:
* `charmcraft pack`' a charm
* then delete a local file
* `charmcraft pack` again

The deleted file does not get removed from the `.charm`

### Expected behaviour
That `charmcraft pack` would produce a charm that reflects what is in my current directory (in this case, **without** the deleted file), regardless of whether it has been run previously or not.  Or, that `charmcraft pack` will fail in cases where it cannot produce a charm reflecting my current directory (and that it gives a helpful error suggesting how to resolve)

**Comment by facundobatista** [comment]
Dup of #710
