### ISSUE TITLE
Support craft_parts.PartsError as a complex object

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#751]
The Craft Parts library raises several errors that inherit its `PartsError`, whose `__str__` method just puts together the error message, details and resolution hints in several lines (concatenates all strings with `\n`). This looks ugly when we show the error.

We need to get that object and build an also complex CraftError from the different `PartsError` attributes. Probably the simplest place to do this in a couple of points in `./charmcraft/parts.py`

**Comment by lengau** [comment]
This will come in with our craft-application migration
