### ISSUE TITLE
Creating bundle leaves metadata file out - no discourse-based documentation possible

### ISSUE THREAD

**Issue by mcjaeger** [canonical/charmcraft#756]
(tested with current version of Charmcraft)

test have shown that when packing a bundle, the `metadata.yaml` is left out. Also downloading bundles from the charmhub.io shows the archive without metadata.yaml in it.

As a result, the chrmhub.io cannot display the referring documentation in discourse, because the link to the discourse page is the `docs:`filed in the `metadata.yaml`file missing.

Example:
1. charm on charmhub.io: https://charmhub.io/linstor/docs
2. ref metadatafile: https://github.com/LINBIT/charmed-linstor/blob/def9580d93807d0905ab432ddbec3484a960eaff/linstor/metadata.yaml#L18
3. ref page on discourse: https://discourse.charmhub.io/t/linstor-docs-index/5939

So the resolution could be just to pull the metadata.yaml into the resulting bundle, currently:
<img width="565" alt="Screenshot 2022-04-25 at 23 23 15" src="https://user-images.githubusercontent.com/3418977/165177379-dac32606-ed6f-4d5c-b3d2-de9215eee262.png">

**Comment by sergiusens** [comment]
@jnsgruk or @jameinel can you confirm that metadata.yaml is part of the spec for bundles?

**Comment by mcjaeger** [comment]
@sergiusens I am sorry, maybe a possible solution proposed leads to other effects, the goal is to have the discourse-based documentation enabled for bundles.

**Comment by jnsgruk** [comment]
Hmm. I don't think that `metadata.yaml` is supposed to be included with a bundle. My guess is that we'd need to support a `docs` key in the `bundle.yaml`? We might need to double check with the store team what they're currently parsing, too.

Also makes me wonder about: https://discourse.charmhub.io/t/charm-metadata-reference/5213/18?u=jnsgruk for bundles.
