### ISSUE TITLE
Dynamically import charmcraft init template

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/charmcraft#762]
Right now there are a few places where a starter can bootstrap their new charm project. The first (most documented) way is charmcraft init; the second would be to clone from a template repo such as
https://github.com/canonical/template-operator
(a personal favourte, there may be more)

My proposal is to make charmcraft init fetch the code from a public template repository.
The default should be https://github.com/canonical/template-operator (main branch)
equivalent:
```
charmcraft init
charmcraft init --branch=main
```

Then we could pass a flag to target a specific branch where we could host for example a machine charm template
```
charmcraft init --branch=machine
```

or a 'minimal' charm template for those among us who don't wish to spend the first 30m on a new project deleting stuff we don't need or use such as (for example) actions.yaml, removing the links to the config from the headers, removing all the httpbin stuff, removing _stored, etc...

Related: #568

**Comment by sed-i** [comment]
This would obviate https://github.com/canonical/charmcraft/issues/542 :+1:

**Comment by PietroPasotti** [comment]
After some internal discussion the conclusion was that we are going to work on charmcraft init profiles.
I wanted to mention that a candidate for one such profile would be: https://github.com/canonical/charm-lib-template

It would be great if one could `charmcraft init --profile lib` and get that template.
Additionally, that template has a `scripts/init.sh` 'install hook', which one is supposed to run to fill in the template further for you.

Maybe we can consider having a uniform 'install hook' location that gets run after 'initializing' the template, and to which one could pass arguments at `charmcraft init` time?

Such as: `charmcraft init --profile lib --charm='charm-name' --lib='lib_name' --version=v0`

So that one doesn't have to remember to `./scripts/init charm-name lib_name v0`.

**Comment by PietroPasotti** [comment]
sorry, didn't mean to close; Enter slipped.
My point with the previous comment is: we can do so much more if we make the templates more templaty, allowing substitutions at init-time.

**Comment by facundobatista** [comment]
Hello! Sorry for the late reply. All substitutions in the template have the corresponding `init` option for the user to set.

Future templates, if they grow more replaceable fields, will make `init` to grow more options for them.

This is what you're asking for, right?

**Comment by rwcarlsen** [comment]
This is basically a request for init profiles (i.e. machine, machine-demo, k8s, k8s-demo, bash, etc.).  However you think it best to implement.  @PietroPasotti's original focus was to accomplish this by allowing charmcraft init to pull from a template repo that we could create different branches on for each profile.  Or we could have a different repo for each profile, etc.  However you decide to go forward, I think people here will be happy if they have the basics covered - e.g. machine-plain, machine-demo, k8s-plain, k8s-demo or whatever we decide to call them.

**Comment by facundobatista** [comment]
Ah, great! Yes, we have too many "init profiles" opened all around. So I'll just close this one. Thanks!!

**Comment by rwcarlsen** [comment]
Notably, I think the idea of template repositories is interesting and probably worth discussing/mentioning in the primary init profiles work.

**Comment by PietroPasotti** [comment]
I think one 'killer' counter-argument to why that is a good idea is: do we want to make charmcraft depend on having an internet connection?

**Comment by rwcarlsen** [comment]
Even if we don't pull them live and have "vendored" them directly into the charmcraft repo, the template code could have an alternatively located home and just be copied into charmcraft.  I agree we shouldn't require being jacked into the nets.
