### ISSUE TITLE
charmcraft V1.5.0 and V1.6.0 not bundling up bash actions

### ISSUE THREAD

**Issue by EMCP** [canonical/charmcraft#763]
I'd been attempting to get Juju team to look into an issue with charmhub, they've sinced said to file a bug against charmcraft

https://bugs.launchpad.net/juju/+bug/1971495/comments/6

"The packaged charm uploaded to charmhub seems to be missing the actions directory.
I packaged a test charm and saw that the actions directory was not included in the charm."

I am currently able to work around this issue by wiring in my charms directly.. please let me know how I can help debug this

Edit : Link to the discourse discussion as well https://discourse.charmhub.io/t/juju-action-only-works-with-local-charm-not-with-charmhub-copy/6022/10?u=emcp

**Comment by facundobatista** [comment]
Yes, you are right! We're missing the directory. We want to do this ASAP. We're tracking the work in issue #764, so I'm closing this issue as duplicated. Thanks for taking the work on reporting the problem!
