### ISSUE TITLE
Show the failure reason when an Upload goes wrong

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#78]
In the UploadCommand, when the result is "not `.ok`", we're telling the user just the status.

We need (after the Server properly tell us) to improve that message.

**Comment by markshuttle** [comment]
As a general rule, please always ask server-side developers to think in terms of status + message

As a basic guideline I would say red-amber-green and a one-liner of text, that fits in under 80 characters. By red-amber-green I mean simply the idea of success, warning, and failure, which are easiest for the client code to handle in a consistent way without knowing the details. Always providing a useful text message helps keep users clear about the issue.

**Comment by facundobatista** [comment]
[This issue](https://bugs.launchpad.net/snapstore-server/+bug/1914787) needs to be solved server side first.
