### ISSUE TITLE
Stop creating scripts under the 'hooks' directory

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#790]
Currently Charmcraft populates the `hooks` directory (creating it if it doesn't exist) with some scripts to make the charm compatible with Juju 2.7 (which only supports the `hooks` directory to send events to the charm).

As that version of Juju has been out of support for quite some time now we can stop adding those scripts if they don't exist.

On the other hand, current Juju still honours the `hooks` directory if present, so we still need to include it by default if present. That said, it's a good idea to add a deprecation notice in the lines of...

    The `hooks` directory (and scripts inside) will stop being included by default 
    in the Charm (as Juju will stop supporting this events mechanism at some 
    point). If you still want to rely on those scripts please use the `prime` directive 
    to include them:

        parts:
          charm:
            prime: 
              - hooks

**Comment by lengau** [comment]
Closing this as no longer planned.

The `charm` and `reactive` plugins will retain their current behaviour. New plugins such as `python` and `poetry` only get a `dispatch` file (and only if no `hooks` are created).
