### ISSUE TITLE
Releasing charms to a channel branch multiple times would create repeated channels 

### ISSUE THREAD

**Issue by agileshaw** [canonical/charmcraft#820]
### Description:
When running `charmcraft release --revision=<rev number> --channel=<risk/branch> <charm name>` multiple times, repeated channel branches with the same name would be created without any warning messages. 

### Example: 
If we pass `beta/fix-1234` as a channel branch to the above command and run it 3 times, the charm would have 3 identical channels listed in `charmcraft status`:
```
ubuntu 20.04 (amd64)   stable         59         59                 
                       candidate      61         61                 
                       beta           ↑          ↑                  
                       edge           61         61                 
                       beta/fix-1234  62         62          2022-08-31T01:00:00Z                                                                   
                       beta/fix-1234  62         62          2022-08-31T01:00:00Z                                                                   
                       beta/fix-1234  62         62          2022-08-31T01:00:00Z  
```

This is a strange and unexpected behavior that creates confusion. I would expect the charmcraft to:
- block the creation of multiple channels with the exact same name
_and/or_
- check the existence of such a channel and release the revision to it
_and/or_
- at minimum, prompt a warning message to the user

**Comment by facundobatista** [comment]
Hello! Thanks for the report.

Question, has the charm multiple architectures? Because I couldn't reproduce this or find a bug regarding "multiple releases", but I found *exactly this behaviour* when the charm has several architectures.

I opened #834 to track that case, can you confirm please that this is the same situation? 

Thanks!

**Comment by agileshaw** [comment]
Hello, thank you for your response and apologize for the late reply.  

I have tested it again and could not reproduce the bug of `multiple releases`, so I think it's safe to close this issue. However, I did notice that this behavior is related to not just the number of architectures, but the number of distinct bases a charm has. I have posed a comment in #834 with my test log.
