### ISSUE TITLE
Download charm libraries on pack instead of running the fetch-lib subcommand

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/charmcraft#841]
I'm proposing to change the approach in which we're adding libraries to the charm to a more "as code" approach, emulating the approach dependency management tools normally use.
I think adding charm libraries in a pip-like format will make easier to check the current library versions and simplify development, and will probably simplify the logic when checking if new versions are available. Developers will also be more familiar with this way of declaring dependencies and won't have to run a command per library.

Thank you!

**Comment by facundobatista** [comment]
Hello! Thanks for the question/suggestion.

The problem with updating all libraries as part of the pack process is that the developer may not want to always have all libraries updated (for sure not changing the major API number, but maybe not even the minor one).

Note that if a library is updated, the charm developer should run all tests for its charm using the updated library. Updating the library at "pack time" will mean that the produced .charm file really was never unit-tested, which is a no-no.

Something we DO want to improve is the alert to the developer that a more updated library version is available (but never update it automatically). We’re tracking that in #510.

Regards,

**Comment by arturo-seijas** [comment]
To ensure repeatable builds we'd just need to enforce providing a specific version. I don't see why that invalidates the proposal. Moreover, it will probably be easier to parse that file looking for the actual version to check if there are updates.

Thank you

**Comment by facundobatista** [comment]
Sorry, I answered to the title of the issue and forgot the to answer to the body of the issue (which seem somewhat disconnected one of the other).

One of the design decisions of the charm libraries is to keep them super simple: we will not be creating a new package management system or make it to behave like

**Comment by arturo-seijas** [comment]
In fact, if implemented this way we could just replicate the dependency updates in the same way [the maven dependency plugin does](https://www.mojohaus.org/versions-maven-plugin/examples/display-dependency-updates.html)

**Comment by arturo-seijas** [comment]
What I'm proposing is to be able to define the required libraries a text file in a format similar to
```
nginx-ingress-integrator.ingress.v0.p26
prometheus-k8s.prometheus_scrape.v0.p21
grafana-k8s.grafana_dashboard.v0.p13
loki-k8s.loki_push_api.v0.p12
```
instead of having to run multiple commands as in
```
charmcraft fetch-lib charm.nginx-ingress-integrator.ingress.v0.p26
charmcraft fetch-lib charm.prometheus-k8s.prometheus_scrape.v0.p21
charmcraft fetch-lib charm.grafana-k8s.grafana_dashboard.v0.p13
charmcraft fetch-lib charm.loki-k8s.loki_push_api.v0.p12
```
and automatically download the specified libraries when packing the charm.

The usage of a patch version could be either enforced or maybe we could warn if it's not set, suggesting to pin it to the last one available.

**Comment by facundobatista** [comment]
Again, downloading the libraries when packing the charm means that the created `.charm` file is not unit-tested. That is something that we do not want to encourage.

**Comment by arturo-seijas** [comment]
> Again, downloading the libraries when packing the charm means that the created `.charm` file is not unit-tested. That is something that we do not want to encourage.

Yes, good point. Sorry about that. Having them defined in the file and checked in the lib directory could lead to inconsistencies, so that doesn't seem like a good solution either.

I guess we've already considered publishing the libs as python packages, right? That would address both my concerns and https://github.com/canonical/charmcraft/issues/510 but I guess it has been discarded for some reason

**Comment by arturo-seijas** [comment]
Noted. Thank you for your help :)

I'm closing the ticket.
