### ISSUE TITLE
As a charmcraft user I wish to be alerted when issue `clean` command on 'bundle' projects

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#856]
The `clean` command works on instances that are used to build charms. Packing bundles don't use these instances, so nothing can be cleaned.

When issuing `charmcraft clean` on a project that is not a charm, it should emit a message saying "Nothing to clean in a project that is not a charm.". Do not raise an error, but finish the command with return code 1.

**Comment by lengau** [comment]
No longer needed since `charmcraft clean` will clean unmanaged locations since 3.0 and bundles are getting retired.
