### ISSUE TITLE
`charmcraft upload-resource` 2.1.0 removes ability to pass tagged image names to `--image` argument

### ISSUE THREAD

**Issue by ca-scribner** [canonical/charmcraft#906]
`charmcraft` 2.1.0 includes [this fix](https://github.com/canonical/charmcraft/pull/871) which patched a bug with how `charmcraft upload-resource --image ____` handled image ID/digests for uploading oci images.  Prior to this patch, `charmcraft upload-resource` would successfully upload images provided by tagged image name (`charmcraft upload-resource --image ubuntu:22.10` worked), but this patch inadvertently blocks this usage because it interprets any input string that includes a `:` as a digest (so `--image ubuntu:22.10` will be interpreted as a digest).  [The upload-resource documentation](https://discourse.charmhub.io/t/charmcrafts-upload-resource-command/4580) states that the `--image` flag accepts only the short digest (aka image id) or the long digest (eg: `sha256:...1), and that *it does not accept the image `name:tag`* for uploading oci images, so there was never intent to allow image uploads by tagged name even though it did function that way prior to version 2.1.0

Although the documentation clearly states image should be specified by ID/digest, a large portion of the charming community has interpreted the `--image` argument as a typical named image reference, as is common in other tools in the ecosystem (example: [kubernetes container spec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#image) uses the name `image` and accepts `imagename:tag` or `imagename@digest`).  This means that 2.1.0 was a breaking change for anyone who used the tool this way.  

At least 2 Canonical teams (~30 charms) had CI that broke from this patch, and [searching Canonical's org for `metadata.yaml` files that reference images by tagged name](https://github.com/search?p=5&q=org%3Acanonical+%22upstream-source%22+filename%3Ametadata.yaml&type=Code) suggests all or nearly all charms are referencing images by tagged name rather than digest.  This means it is likely this is an accidental breaking change for others as well.

It would be helpful if this change was reverted (or modified so that tagged images were allowed).  If the requirement is to not use tagged image names, a deprecation period seems appropriate given its wide use.  It would also be helpful if `charmcraft`'s integration testing include some of the community's charms and tooling so that breaking changes (even if they adhere to the stated behaviour of the tool) are caught before reaching production.

**Comment by sergiusens** [comment]
I agree; once something is used it cannot simply go away as bugs become features.
The only place to change this (if we follow semantic versioning) is for the major version to change to signal a form of change approaching.

I had the impression from chat that this was solved, but updating everything else should not have been the solution.

**Comment by sergiusens** [comment]
FWIW, there's a test task in place to test actual charms https://github.com/canonical/charmcraft/tree/main/tests/spread/charms

What remains now is to test the action.

**Comment by ca-scribner** [comment]
I think most of the disruption will be mitigated by end of today.  

The obs and kubeflow teams are patching their github action that uploads charms to pass a digest to charmcraft rather than an image name.  That should be reviewed and released today, so the kubeflow/obs teams should be unblocked by end of day (after bumping the version of our CI).  We seemed to be the most vocal customer affected.

Anyone else passing image names to charmcraft like we were will need to figure out on their own what went wrong and how to fix it.  Hard to tell how many there are out there, but pushing a charmcraft 2.1.1 that tells them why things are failing would help.

Can't go back in time, but imo this feels like something where when a few teams report they're blocked we should have reverted the charm version first and then discussed how to handle it further.  The scope of what was fixed in 2.1.0 was much smaller than the scope of what was reported broken by 2.1.0.  Maybe another lesson to learn here is to define how teams can ask for a reversion.  It wasn't critical this time (lost a few people hours of work discussing and fixing on the user side), but if this was in the middle of a release deadline it could have been a problem.

**Comment by ca-scribner** [comment]
Good to see there's actual charms in the test suite, and yes it would be great to add in some of the automated CI we use.  We can help with that however you need.  

To be fair, it would have been really difficult to think of this as a test ahead of time.  As long as we're learning from this and making tests from it that's a good outcome

**Comment by facundobatista** [comment]
Hello! First of all, sorry for the disturbance. This being not just a simple bug but a situation that we explicitly wanted to avoid at first, was a special case.

I'm glad to hear that you already migrated (most of?) your systems to use digest or image id, but let me know if you are blocked on any of those and we may be able to craft something to keep it working until you fix it.

Regarding charmcraft improvements, we should make explicit that tags are not allowed; instead of confuse them with digests and fail to find them, we should detect that a tag was used and provide a better message to the user. I opened #912 for that.

But also it would be great if we catch these problems earlier. As Sergio noted above we're already packing those charms, but the issue impacted in the Github's CI. Not sure what would be the best way to support this. Do you have any idea? Thanks!

**Comment by sergiusens** [comment]
I believe this is solved, not in the best way, but solved alas, if we need further discussion on this, feel free to re-open
