### ISSUE TITLE
Make explicit that image resources are not uploadable by tag

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#912]
We only support uploading image resources using the image id or its digest, not its tag.

Currently, however, if you write `--image=myrepo:stable` charmcraft thinks that the passed string is a digest, and fails to find it. It should detect that it's a tag and fail with an error like "The --image option must refer to an image id or a digest, not a tag.", to simplify user correction.

Futrthermore, the documentation should explicit that tags are not supported.

**Comment by facundobatista** [comment]
We should just deprecate `--image` to stop ambiguities, and just provide two explicit (exclusive) options: `--image-id` and `--image-digest` (and also document that "by tag" is not supported!)

**Comment by lengau** [comment]
This is no longer relevant with charmcraft 3
