### ISSUE TITLE
Documentation by channel

### ISSUE THREAD

**Issue by jdkandersson** [canonical/charmcraft#935]
Currently, the `docs` key in `metadata.yaml` points to a discourse post for the docs of a charm. It is possible to maintain different documentation by channel by supplying different values to the `docs` key. However, it is easy to forget to correct the value of `docs` before publishing to a particular channel. Would it be possible to have different links in `metadata.yaml` depending on the targeted channel? I guess this would also require changes to charmhub to interpret the links by channel

**Comment by facundobatista** [comment]
Hello! 

The `metadata.yaml` file is designed and maintained by the Juju project, you should open this request there: https://bugs.launchpad.net/juju/+filebug

Thanks!!
