### ISSUE TITLE
Add yaml formatting feature in charmcraft status 

### ISSUE THREAD

**Issue by rahulsinghcanonical** [canonical/charmcraft#940]
Currently only 'json' format is supported for `charmcraft status <charm_name> --format json`. The format option can be extended to yaml with simple code change as this will give the user the option to output the status in YAML format which is considered more readable format.

**Comment by facundobatista** [comment]
Hello @rahulsinghcanonical ! Thanks for the report. 

Humans would not use the `--format` option at all and would receive a curated output. The `--format` is used to be consumed by other processs, so being YAML more readable than JSON would not be a factor there.

Am I missing something in your proposal? Thanks!

**Comment by rahulsinghcanonical** [comment]
@facundobatista yes, I agree with the statement. Closing this issue as this does not enhance the feature of charmcraft.
