### ISSUE TITLE
Listings (and other "output", as contrasted to messages) should go to stdout not stderr

### ISSUE THREAD

**Issue by chipaca** [canonical/charmcraft#95]

**Comment by facundobatista** [comment]
How and where all the messages should go [is specified here](https://docs.google.com/document/d/1Pe-0ED6db53SmrUGIAgVMzxeCOGJQwsZJWf7jzFSagQ/).

**Comment by facundobatista** [comment]
This is provided now by the craft-cli library, integrated already!
