### ISSUE TITLE
Discussion: Send python3 with the charm

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#98]
In the pursuit of supporting operating system agnostic charms, we are trying to account for the case in which python3 isn't installed in the system at the time the charm code tries to run. We have tried a few different options in getting python3 installed prior to running charm code; supplying cloudinit-userdata to the model config that installs python3, [this whole run around](https://discourse.juju.is/t/putting-dependencies-in-place-prior-to-running-charm-code/3375), and other unmentionable acts.

I'm wondering if we can solve this by packaging python3 in the `.charm` when we run `charmcraft build`?

I've worked out a bit of code that creates the venv and adds python3 to the charm [here](https://github.com/jamesbeedy/charmcraft/commit/7934f86146cb678b87a5d858d1a9bf17c0b67cda)

The above adds python3 to the `.charm` file which in turn enables us to deploy the charm without worrying about whether or not python3 exists on the system.

The only remaining issue here is that we also need GLIBC to exist for python3 to work.

**Comment by jameinel** [comment]
I think it would be possible to do this, but as you noted, it still has trouble with things like GLIBC. Figuring out how to get a appropriately-contained charm running on various platforms is definitely something we want to figure out.
I'm not sure that Python is the right answer, but it might be. It does end up bloating the charm, and you end up having to deal with security issues, etc that the platform/distro is already handling for you.
It also came up with charms that want to cross many different series (support Trusty-Focal) and not just charms that cross OS (Redhat vs Ubuntu)

**Comment by facundobatista** [comment]
We'll have this functionality for free when we get the whole packing lifecycle a-la-snapcraft.

**Comment by sergiusens** [comment]
@jamesbeedy with craft-parts now integrated in 1.2 you can perhaps start exploring this just like you did in snapcraft. I guess this would be the equivalent of a classic snap, so care would be needed.
