### ISSUE TITLE
Drop year(s) from all copyright headers?

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#982]
Currently all our files have year(s) in the header.

https://github.com/canonical/charmcraft/blob/a6c21119c4dd72d289faa54cf713e425d508684e/charmcraft/templates/init-kubernetes/src/charm.py.j2#L2

Any chance we could do [copyright without years](https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/)?

**Comment by lengau** [comment]
I'm personally a fan of getting rid of the years in the copyright statement. Are there any other Canonical projects that are doing so (and could we make it a Canonical-wide effort)?

**Comment by facundobatista** [comment]
The year in the Copyright header is a legal requirement from the Canonical's Operations department, so all Canonical projects should have it.

We *could* remove it from the template, but if it's a good idea for other projects (e.g. Charmcraft itself), it's probably a good idea for initialised charms... so I'm closing this as "wont fix", thanks!
